import {useEffect,useState} from 'react';
import {EmptyState,PageHeader,Panel,StatusChip} from '../../design-system';
import {listChampionships,listProviders,quotaDiagnostics,syncRuns,syncStreams,type Provider,type ProviderChampionship,type QuotaDiagnostics,type SyncRun,type SyncStream} from '../provider-sources/sourcesApi';

type SchedulerRow={provider:Provider;championship:ProviderChampionship;stream:SyncStream;lastRun:SyncRun|null;quota:QuotaDiagnostics|null};
const date=(value:string|null|undefined)=>value?new Intl.DateTimeFormat('fr-FR',{dateStyle:'short',timeStyle:'short'}).format(new Date(value)):'—';
export const schedulerWorkClass=(stream:SyncStream)=>stream.phase==='current'?'current':String(stream.cursor?.work_class??'deep_history');
export const schedulerWaitReason=(stream:SyncStream,quota:QuotaDiagnostics|null)=>stream.stream_backoff_until?'Backoff du flux':quota?.summary.blocking_reason??(stream.next_eligible_at?'Cadence calculée':stream.state==='running'?'En cours':'Éligible');
const label:Record<string,string>={current:'Données actuelles',recent_catchup:'Année courante',deep_history:'Historique profond',finalization:'Finalisation'};
const tone=(state:string)=>/error|suspend|failed/.test(state)?'red':/wait|backoff|pending|paused/.test(state)?'amber':/running|ready|active|complete/.test(state)?'green':'muted';

export function SchedulerPage(){
  const[rows,setRows]=useState<SchedulerRow[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
  async function load(){setLoading(true);setError('');try{const providers=await listProviders();const groups=await Promise.all(providers.map(async provider=>{const [links,quota]=await Promise.all([listChampionships(provider.id),quotaDiagnostics(provider.id).catch(()=>null)]);return Promise.all(links.map(async championship=>{const[streams,runs]=await Promise.all([syncStreams(championship.id),syncRuns(championship.id)]);return streams.map(stream=>({provider,championship,stream,lastRun:runs.find(run=>run.work_class===schedulerWorkClass(stream))??runs[0]??null,quota}));}));}));setRows(groups.flat(2));}catch(reason){setError((reason as Error).message)}finally{setLoading(false)}}
  useEffect(()=>{void load()},[]);
  return <><PageHeader title="SCHEDULER" subtitle="Supervision de l’ordonnancement dynamique" action={<button onClick={()=>void load()}>Actualiser</button>}/><div className="sources-boundary">La cadence et la prochaine tentative sont calculées automatiquement selon les priorités, quotas, backoffs, leases et règles d’équité. Aucune fréquence cron n’est requise.</div>{error&&<div className="sources-error" role="alert">{error}</div>}<Panel title="FLUX PERSISTANTS">{loading?<p className="sources-loading">Chargement…</p>:rows.length===0?<EmptyState text="Aucun flux de synchronisation configuré."/>:<div className="scheduler-table-wrap"><table className="data-table scheduler-table"><thead><tr><th>PROVIDER / CHAMPIONNAT</th><th>CLASSE</th><th>PRIORITÉ</th><th>ÉTAT</th><th>DERNIÈRE PROGRESSION</th><th>PROCHAINE ÉLIGIBILITÉ</th><th>RAISON D’ATTENTE</th><th>QUOTA</th><th>LEASE / RETRY</th></tr></thead><tbody>{rows.map(({provider,championship,stream,lastRun,quota})=>{const work=schedulerWorkClass(stream),boost=stream.priority_boost_until&&new Date(stream.priority_boost_until)>new Date();return <tr key={stream.id}><td><b>{provider.name}</b><small>{championship.championship_name}</small></td><td>{label[work]??work}</td><td>{boost?'Boost opérateur':work==='current'?'Haute (poids 3)':work==='recent_catchup'?'Normale (poids 2)':'Arrière-plan (poids 1)'}</td><td><StatusChip text={stream.state.toUpperCase()} tone={tone(stream.state)}/></td><td>{date(stream.last_progress_at)}<small>{lastRun?`Dernier run : ${lastRun.status}`:'Aucun run'}</small></td><td>{date(stream.next_eligible_at??quota?.summary.next_eligible_at)}</td><td>{schedulerWaitReason(stream,quota)}</td><td>{quota?.summary.state??'indisponible'}<small>{quota?.summary.remaining_estimated==null?'Restant inconnu':`${quota.summary.remaining_estimated} restant(s)`}</small></td><td>{stream.lease_owner?'Lease actif':'Aucun lease'}<small>{stream.stream_backoff_until?`Backoff jusqu’au ${date(stream.stream_backoff_until)}`:`Retries : ${stream.stream_failure_count??0}`}</small></td></tr>})}</tbody></table></div>}</Panel></>;
}
