import {describe,expect,it} from 'vitest';
import {advanceDeepHistory,civilDayEndUtc,classifyCurrentInstant,currentPrioritySequence,estimateTheoreticalEnd,isFinalizationEligible,nextBootstrapWork} from '../src/providers/acquisitionOrchestrator.js';

describe('orchestration acquisition 5.6-D',()=>{
  const now=new Date('2026-03-29T00:00:00Z');
  it('classe hot et futur sans couper après J+30',()=>{expect(classifyCurrentInstant(new Date('2026-04-28T23:59:59Z'),now,30)).toBe('current_hot');expect(classifyCurrentInstant(new Date('2027-01-01T00:00:00Z'),now,30)).toBe('current_future');});
  it('conserve une séquence current globale sans parcours future dupliqué',()=>{expect(currentPrioritySequence).not.toContain('current_future');expect(currentPrioritySequence[0]).toBe('finalization');expect(currentPrioritySequence).toContain('current_hot');});
  it('ordonne bootstrap sans doubler le parcours current global',()=>{expect(nextBootstrapWork({bootstrap_state:'pending',recent_catchup_state:'pending',deep_history_state:'pending',current_stage:'hot'})).toBe('finalization');expect(nextBootstrapWork({bootstrap_state:'pending',recent_catchup_state:'pending',deep_history_state:'pending',current_stage:'hot'},0,'historical')).toBe(null);expect(nextBootstrapWork({bootstrap_state:'recent_catchup',recent_catchup_state:'pending',deep_history_state:'pending',current_stage:'hot'},0,'historical')).toBe('recent_catchup');expect(nextBootstrapWork({bootstrap_state:'deep_history',recent_catchup_state:'complete',deep_history_state:'running',current_stage:'hot'},0,'historical')).toBe('deep_history');expect(nextBootstrapWork({bootstrap_state:'deep_history',recent_catchup_state:'complete',deep_history_state:'running',current_stage:'hot'},4,'current')).toBe('finalization');});
  it('ne compte que les saisons vides complètes',()=>{const base={season:2020,consecutiveEmpty:4,emptyLimit:5,historyFromSeason:null,mode:'all' as const};expect(advanceDeepHistory({...base,outcome:{complete:false,emptyConfirmed:true,receivedItems:0}})).toMatchObject({season:2020,consecutiveEmpty:4,changed:false});expect(advanceDeepHistory({...base,outcome:{complete:true,emptyConfirmed:true,receivedItems:0}})).toMatchObject({season:2019,consecutiveEmpty:5,complete:true});});
  it('remet le compteur à zéro sur saison non vide',()=>expect(advanceDeepHistory({season:2020,consecutiveEmpty:4,emptyLimit:5,historyFromSeason:null,mode:'all',outcome:{complete:true,emptyConfirmed:false,receivedItems:1}})).toMatchObject({consecutiveEmpty:0,complete:false}));
  it('respecte la borne historique configurée',()=>expect(advanceDeepHistory({season:1950,consecutiveEmpty:0,emptyLimit:5,historyFromSeason:1950,mode:'from_season',outcome:{complete:true,emptyConfirmed:false,receivedItems:1}}).complete).toBe(true));
  it('hiérarchise les fins théoriques',()=>{const start=new Date('1950-05-13T10:00:00Z'),provider=new Date('1950-05-13T12:00:00Z');expect(estimateTheoreticalEnd({start,providerEnd:provider})).toEqual({end:provider,estimated:false,provenance:'provider'});expect(estimateTheoreticalEnd({start,sessionEnds:[provider]}).provenance).toBe('last_known_session');expect(estimateTheoreticalEnd({start,comparableDurationsMs:[1000,3000,2000]}).end.getTime()).toBe(start.getTime()+2000);expect(estimateTheoreticalEnd({start,comparableDurationsMs:[1000,2000],adapterDurationMs:4000}).provenance).toBe('adapter_rule');expect(estimateTheoreticalEnd({start,civilDayEnd:provider}).provenance).toBe('civil_day_fallback');});
  it('applique la fenêtre de finalisation sans forcer un statut',()=>{const end=new Date('2026-01-01T00:00:00Z');expect(isFinalizationEligible(end,new Date('2026-01-31T00:00:00Z'),30)).toBe(true);expect(isFinalizationEligible(end,new Date('2026-02-01T00:00:01Z'),30)).toBe(false);});
  it('supporte minuit, DST et pré-1970 comme instants',()=>{expect(classifyCurrentInstant(new Date('1969-12-31T23:59:59Z'),new Date('1969-12-31T00:00:00Z'),1)).toBe('current_hot');expect(classifyCurrentInstant(new Date('2026-03-30T00:00:00Z'),now,1,'Europe/Paris')).toBe('current_hot');expect(civilDayEndUtc(new Date('2026-03-29T10:00:00Z'),'Europe/Paris').toISOString()).toBe('2026-03-29T21:59:59.999Z');expect(civilDayEndUtc(new Date('1969-12-31T10:00:00Z'),'UTC').toISOString()).toBe('1969-12-31T23:59:59.999Z');});
});
