import Fastify from 'fastify';
import {readFileSync} from 'node:fs';
import {describe,expect,it,vi} from 'vitest';
import {decodeCursor,encodeCursor,type PageCursor} from '../src/preview/cursors.js';
import type {PreviewRepository,ResourceRow} from '../src/preview/repository.js';
import {previewReadRoutes} from '../src/routes/previewRead.js';

const SECRET='preview-cursor-test-secret-at-least-32-characters';
const NOW=new Date('2026-08-22T12:00:00.000Z');
const ids=['57000000-0000-4000-8000-000000000101','57000000-0000-4000-8000-000000000102','57000000-0000-4000-8000-000000000103'];
const rows:ResourceRow[]=ids.map((resourceId,index)=>({resourceType:'event',resourceId,revision:index+1,lifecycle:'active',promotedAt:NOW.toISOString(),sortKey:`2026-09-0${index+1}T12:00:00.000Z`,state:{resourceKind:'event',name:`Race ${index+1}`,sessionType:'race',sessionLabel:'Race',status:'scheduled',championshipId:ids[0],circuitId:ids[1],startsAt:`2026-09-0${index+1}T12:00:00.000Z`,endsAt:null,timezone:'UTC',presence:'seen',provider_key:'must-not-leak',provenance:{private:true}}}));

function repository(overrides:Partial<PreviewRepository>={}):PreviewRepository{return {snapshotBoundary:vi.fn().mockResolvedValue(12),oldestSnapshotSequence:vi.fn().mockResolvedValue(0),oldestChangeSequence:vi.fn().mockResolvedValue(1),resolveChampionship:vi.fn().mockResolvedValue(ids[0]),list:vi.fn().mockImplementation(async input=>rows.slice(0,input.limit+1)),detail:vi.fn().mockResolvedValue(rows[0]),changes:vi.fn().mockResolvedValue([{sequence:13,resourceType:'event',resourceId:ids[0],revision:2,operation:'updated',changedFields:['startsAt'],occurredAt:NOW.toISOString(),current:rows[0]}]),...overrides};}
async function application(repo=repository()){const app=Fastify({logger:false});await app.register(previewReadRoutes,{repository:repo,cursorSecret:SECRET,now:()=>NOW});return app;}

describe('5.7-P-D Preview read API',()=>{
  it('returns an enveloped bounded collection with distinct opaque cursors and no internal fields',async()=>{const repo=repository(),app=await application(repo);const response=await app.inject('/api/v1/events?limit=2&status=scheduled&session_type=race');expect(response.statusCode).toBe(200);const body=response.json();expect(body.data).toHaveLength(2);expect(body.pagination.has_more).toBe(true);expect(body.pagination.next_cursor).not.toBe(body.pagination.sync_cursor);expect(JSON.stringify(body)).not.toMatch(/provider|provenance|payload|score|correction/i);expect(repo.list).toHaveBeenCalledWith(expect.objectContaining({resourceType:'event',limit:2,status:'scheduled',sessionType:'race',from:NOW.toISOString()}));await app.close();});
  it('rejects unknown, mutually exclusive, oversized and forged inputs before querying',async()=>{const repo=repository(),app=await application(repo);for(const url of [`/api/v1/events?unknown=x`,`/api/v1/events?championship=f1&championship_id=${ids[0]}`,`/api/v1/events?limit=101`,`/api/v1/events?cursor=${'x'.repeat(2049)}`,`/api/v1/events?cursor=forged.value`])expect((await app.inject(url)).statusCode,url).toBe(400);expect(repo.list).not.toHaveBeenCalled();await app.close();});
  it('keeps page and sync cursors type-separated and signed',async()=>{const repo=repository(),app=await application(repo);const page=encodeCursor({kind:'page',resourceType:'event',snapshotSequence:12,sortKey:rows[0].sortKey,resourceId:ids[0],filterHash:'a'.repeat(43),issuedAt:1},SECRET);const sync=encodeCursor({kind:'sync',sequence:12,issuedAt:1},SECRET);expect((await app.inject(`/api/v1/events?cursor=${sync}`)).statusCode).toBe(400);expect((await app.inject(`/api/v1/changes?cursor=${page}`)).statusCode).toBe(400);expect(()=>decodeCursor(`${sync}x`,'sync',SECRET)).toThrow('cursor_invalid');await app.close();});
  it('binds a page cursor to the original filters and effective future boundary',async()=>{const repo=repository(),app=await application(repo);const first=(await app.inject('/api/v1/events?limit=2&status=scheduled')).json();expect((await app.inject(`/api/v1/events?limit=2&status=completed&cursor=${first.pagination.next_cursor}`)).statusCode).toBe(400);const continued=await app.inject(`/api/v1/events?limit=2&status=scheduled&cursor=${first.pagination.next_cursor}`);expect(continued.statusCode).toBe(200);expect(repo.list).toHaveBeenLastCalledWith(expect.objectContaining({from:NOW.toISOString(),status:'scheduled'}));await app.close();});
  it('returns monotone changes, current data and a resumable cursor',async()=>{const repo=repository(),app=await application(repo);const response=await app.inject('/api/v1/changes?include=data&limit=1');expect(response.statusCode).toBe(200);const body=response.json();expect(body.data[0]).toMatchObject({sequence:13,resource_type:'event',operation:'updated',changed_fields:['startsAt']});expect(body.data[0].current.id).toBe(ids[0]);expect(decodeCursor(body.pagination.next_cursor,'sync',SECRET)).toMatchObject({sequence:13});await app.close();});
  it('uses the retained journal boundary rather than issuedAt for sync expiry',async()=>{const old=Math.floor(new Date('2026-01-01T00:00:00Z').valueOf()/1000),retained=encodeCursor({kind:'sync',sequence:12,issuedAt:old},SECRET),expired=encodeCursor({kind:'sync',sequence:11,issuedAt:Math.floor(NOW.valueOf()/1000)},SECRET);const app=await application(repository({oldestChangeSequence:vi.fn().mockResolvedValue(12)}));expect((await app.inject(`/api/v1/changes?cursor=${retained}`)).statusCode).toBe(200);const gone=await app.inject(`/api/v1/changes?cursor=${expired}`);expect(gone.statusCode).toBe(410);expect(gone.json().error).toMatchObject({code:'sync_cursor_expired',request_id:expect.any(String)});await app.close();});
  it('returns safe structured errors for invalid future sequences, expired snapshots and database failures',async()=>{const future=encodeCursor({kind:'sync',sequence:13,issuedAt:1},SECRET),bounded=await application(repository({oldestSnapshotSequence:vi.fn().mockResolvedValue(5)}));expect((await bounded.inject(`/api/v1/changes?cursor=${future}`)).statusCode).toBe(400);const first=(await bounded.inject('/api/v1/events?limit=2')).json(),decoded=decodeCursor(first.pagination.next_cursor,'page',SECRET) as PageCursor,expiredPage=encodeCursor({...decoded,snapshotSequence:4},SECRET);expect((await bounded.inject(`/api/v1/events?limit=2&cursor=${expiredPage}`)).statusCode).toBe(410);await bounded.close();const failed=await application(repository({list:vi.fn().mockRejectedValue(new Error('SQL secret stack'))}));const response=await failed.inject('/api/v1/events');expect(response.statusCode).toBe(500);expect(response.json().error).toMatchObject({code:'internal_error'});expect(response.body).not.toMatch(/SQL|secret|stack/);await failed.close();});
  it('returns tombstones as null current data and validates UUID details',async()=>{const repo=repository({changes:vi.fn().mockResolvedValue([{sequence:14,resourceType:'event',resourceId:ids[0],revision:3,operation:'removed',changedFields:[],occurredAt:NOW.toISOString(),current:null}])}),app=await application(repo);expect((await app.inject('/api/v1/changes?include=data')).json().data[0].current).toBeNull();expect((await app.inject('/api/v1/events/not-a-uuid')).statusCode).toBe(400);await app.close();});
  it('keeps the OpenAPI contract synchronized with the seven definitive V1 routes',()=>{const document=JSON.parse(readFileSync(new URL('../../../docs/api-v1-preview.openapi.json',import.meta.url),'utf8'));expect(Object.keys(document.paths).sort()).toEqual(['/championships','/championships/{id}','/changes','/events','/events/{id}','/meetings','/meetings/{id}']);expect(JSON.stringify(document)).not.toContain('/preview');expect(document.paths['/events'].get.parameters.find((item:{name?:string})=>item.name==='limit')??document.components.parameters.Limit).toBeDefined();expect(document.paths['/changes'].get.responses['410'].description).toBe('sync_cursor_expired');});
});
