import Fastify from 'fastify';
import {describe,expect,it,vi} from 'vitest';
import {constantTimeDigestEqual,type ApiClientPrincipal,type PreviewClientSecurityService} from '../src/preview/clientSecurity.js';
import type {PreviewRepository,ResourceRow} from '../src/preview/repository.js';
import {previewClientAdminRoutes,previewSecurityRoutes} from '../src/routes/previewSecurity.js';

const SECRET='preview-cursor-test-secret-at-least-32-characters',clientId='57000000-0000-4000-8000-000000000001',championshipId='57000000-0000-4000-8000-000000000002',resourceId='57000000-0000-4000-8000-000000000003';
const principal:ApiClientPrincipal={clientId,keyId:resourceId,scopes:new Set(['championships:read','events:read','meetings:read','changes:read']),championshipIds:new Set([championshipId]),rateLimit:60,dailyQuota:10000,pageLimit:100,changesPageLimit:500};
const row:ResourceRow={resourceType:'event',resourceId,revision:1,lifecycle:'active',promotedAt:'2026-08-24T00:00:00.000Z',sortKey:'2026-08-25T00:00:00.000Z',state:{name:'Race',championshipId,startsAt:'2026-08-25T00:00:00.000Z'}};
const repository=(overrides:Partial<PreviewRepository>={}):PreviewRepository=>({snapshotBoundary:vi.fn().mockResolvedValue(1),oldestSnapshotSequence:vi.fn().mockResolvedValue(0),oldestChangeSequence:vi.fn().mockResolvedValue(0),resolveChampionship:vi.fn().mockResolvedValue(championshipId),list:vi.fn().mockResolvedValue([row]),detail:vi.fn().mockResolvedValue(row),changes:vi.fn().mockResolvedValue([]),...overrides});
const security=(overrides:Record<string,unknown>={})=>({verify:vi.fn().mockResolvedValue(principal),charge:vi.fn().mockResolvedValue({allowed:true,minute:new Date(),day:'2026-08-24',minuteRemaining:59,dailyRemaining:9999,retryAfter:60}),refundDaily:vi.fn().mockResolvedValue(undefined),...overrides}) as unknown as PreviewClientSecurityService;
async function app(service=security(),repo=repository()){const instance=Fastify({logger:false});await instance.register(previewSecurityRoutes,{security:service,repository:repo,cursorSecret:SECRET,now:()=>new Date('2026-08-24T12:00:00Z')});return instance;}

describe('5.7-P-E Preview client security',()=>{
  it('uses timing-safe fixed-size digest comparison',()=>{expect(constantTimeDigestEqual('a'.repeat(64),'a'.repeat(64))).toBe(true);expect(constantTimeDigestEqual('a'.repeat(64),'b'.repeat(64))).toBe(false);expect(constantTimeDigestEqual('aa','bbbb')).toBe(false);});
  it('returns generic 401 for missing and malformed credentials',async()=>{const service=security({verify:vi.fn().mockResolvedValue(null)}),instance=await app(service);for(const headers of [{},{authorization:'Basic bad'},{authorization:'Bearer malformed'}]){const response=await instance.inject({url:'/api/v1/events',headers});expect(response.statusCode).toBe(401);expect(response.body).not.toMatch(/digest|pepper|authorization|malformed/i);}await instance.close();});
  it('separates scopes from championship entitlement and prevents UUID enumeration',async()=>{const withoutScope={...principal,scopes:new Set(['championships:read'] as const)},scopeApp=await app(security({verify:vi.fn().mockResolvedValue(withoutScope)}));expect((await scopeApp.inject({url:'/api/v1/events',headers:{authorization:'Bearer key'}})).json().error.code).toBe('insufficient_scope');await scopeApp.close();const withoutDataset={...principal,championshipIds:new Set<string>()},entitlementApp=await app(security({verify:vi.fn().mockResolvedValue(withoutDataset)}));expect((await entitlementApp.inject({url:`/api/v1/events?championship_id=${championshipId}`,headers:{authorization:'Bearer key'}})).statusCode).toBe(403);expect((await entitlementApp.inject({url:`/api/v1/events/${resourceId}`,headers:{authorization:'Bearer key'}})).statusCode).toBe(404);await entitlementApp.close();});
  it('charges successful and conditional 304 responses and emits limit headers',async()=>{const service=security(),instance=await app(service);const first=await instance.inject({url:'/api/v1/events',headers:{authorization:'Bearer key'}});expect(first.statusCode).toBe(200);expect(first.headers['ratelimit-limit']).toBe('60');const second=await instance.inject({url:'/api/v1/events',headers:{authorization:'Bearer key','if-none-match':String(first.headers.etag)}});expect(second.statusCode).toBe(304);expect((service.charge as any).mock.calls).toHaveLength(2);await instance.close();});
  it('refunds daily quota for 5xx and returns distinct atomic limiter failures',async()=>{const failedSecurity=security(),failed=await app(failedSecurity,repository({list:vi.fn().mockRejectedValue(new Error('private SQL'))}));expect((await failed.inject({url:'/api/v1/events',headers:{authorization:'Bearer key'}})).statusCode).toBe(500);expect(failedSecurity.refundDaily).toHaveBeenCalledWith(clientId,'2026-08-24');await failed.close();for(const code of ['rate_limit_exceeded','daily_quota_exceeded'] as const){const limited=await app(security({charge:vi.fn().mockResolvedValue({allowed:false,code,retryAfter:30,minuteRemaining:0,dailyRemaining:0})}));const response=await limited.inject({url:'/api/v1/events',headers:{authorization:'Bearer key'}});expect(response.statusCode).toBe(429);expect(response.json().error.code).toBe(code);expect(response.headers['retry-after']).toBe('30');await limited.close();}});
  it('binds cursors to the client across key rotation',async()=>{const instance=await app();const first=(await instance.inject({url:'/api/v1/events',headers:{authorization:'Bearer first-key'}})).json();const rotated=await instance.inject({url:`/api/v1/changes?cursor=${first.pagination.sync_cursor}`,headers:{authorization:'Bearer rotated-key'}});expect(rotated.statusCode).toBe(200);const other={...principal,clientId:resourceId},otherClient=await app(security({verify:vi.fn().mockResolvedValue(other)}));expect((await otherClient.inject({url:`/api/v1/changes?cursor=${first.pagination.sync_cursor}`,headers:{authorization:'Bearer other'}})).statusCode).toBe(400);await instance.close();await otherClient.close();});
  it('provides only the minimal manual ACP lifecycle operations',async()=>{const service={createClient:vi.fn().mockResolvedValue({id:clientId}),createKey:vi.fn().mockResolvedValue({id:resourceId,api_key:'shown-once'}),setStatus:vi.fn().mockResolvedValue({id:clientId,status:'suspended'}),revokeKey:vi.fn().mockResolvedValue({id:resourceId,status:'revoked'}),replaceRights:vi.fn().mockResolvedValue({id:clientId})} as unknown as PreviewClientSecurityService,instance=Fastify({logger:false});await instance.register(previewClientAdminRoutes,{security:service});expect((await instance.inject({method:'POST',url:'/api/v1/admin/api-clients',payload:{name:'F1 client',scopes:['events:read'],championship_ids:[championshipId]}})).statusCode).toBe(201);expect((await instance.inject({method:'POST',url:`/api/v1/admin/api-clients/${clientId}/keys`,payload:{environment:'live',name:'primary'}})).json().api_key).toBe('shown-once');expect((await instance.inject({method:'POST',url:`/api/v1/admin/api-clients/${clientId}/status`,payload:{status:'suspended'}})).statusCode).toBe(200);expect((await instance.inject({method:'POST',url:`/api/v1/admin/api-keys/${resourceId}/revoke`})).statusCode).toBe(200);expect((await instance.inject({method:'PUT',url:`/api/v1/admin/api-clients/${clientId}/rights`,payload:{scopes:['events:read'],championship_ids:[championshipId],rate_limit_per_minute:60,daily_quota:10000,page_limit:100,changes_page_limit:500}})).statusCode).toBe(200);expect(instance.hasRoute({method:'GET',url:'/api/v1/admin/api-clients/self-service'})).toBe(false);await instance.close();});
});
