import { describe,expect,it } from 'vitest';
import { OcBlackTopAdapter,TheSportsDbAdapter,type AdapterCatalogEntry } from '../src/providers/realAdapters.js';
import { fetchProviderJson } from '../src/providers/providerHttp.js';

const response=(value:unknown,status=200)=>Promise.resolve(new Response(JSON.stringify(value),{status,headers:{'content-type':'application/json'}}));
const context=(base_url:string,api_key='test-key',discovery_complete?:boolean)=>({providerInstanceId:'provider',providerConfig:{base_url,...(discovery_complete===undefined?{}:{discovery_complete})},credentials:{api_key},requestCounter:{count:0,increment(){this.count++;},get value(){return this.count;}}});

describe('Lot 5.3 real provider discovery adapters',()=>{
  it('uses a declarative OCBlackTop catalog with three interchangeable strategies',async()=>{const catalog:AdapterCatalogEntry[]=[{externalId:'series-a',name:'A',strategy:'strategy-a',endpointTemplate:'/{series}/events'},{externalId:'series-b',name:'B',strategy:'strategy-b',endpointTemplate:'/{series}/seasons/{year}'},{externalId:'series-c',name:'C',strategy:'synthetic-third-strategy',endpointTemplate:'/catalog/{series}'}];const adapter=new OcBlackTopAdapter(undefined,catalog);const result=await adapter.discoverChampionships(context('https://api.ocblacktop.com/v1'));expect(result).toMatchObject({complete:true,provenance:'adapter-known-catalog'});expect(result.items.map(item=>item.sourceConfig.strategy)).toEqual(['strategy-a','strategy-b','synthetic-third-strategy']);});
  it('accepts a safe future OCBlackTop series without treating the catalog as a whitelist',()=>{const adapter=new OcBlackTopAdapter(undefined,[]);expect(adapter.validateSourceConfig({external_id:'future-series',strategy:'series-events-v1',endpoint_template:'/{series}/events'},{providerConfig:{base_url:'https://api.ocblacktop.com/v1'}})).toMatchObject({external_id:'future-series'});});
  it('discovers WRC as an OCBlackTop seasonal strategy and accepts the same strategy for future series',async()=>{const adapter=new OcBlackTopAdapter();const result=await adapter.discoverChampionships(context('https://api.ocblacktop.com/v1'));const wrc=result.items.find(item=>item.externalChampionshipId==='wrc');expect(wrc?.sourceConfig).toEqual({strategy:'season-rallies-v1',external_id:'wrc',endpoint_template:'/{series}/seasons/{year}'});expect(adapter.validateSourceConfig({strategy:'season-rallies-v1',external_id:'future-rally',endpoint_template:'/{series}/seasons/{year}'},{providerConfig:{base_url:'https://api.ocblacktop.com/v1'}})).toMatchObject({external_id:'future-rally'});});
  it.each([{strategy:'future-strategy',external_id:'future-series',endpoint_template:'/{series}/events'},{strategy:'series-events-v1',external_id:'../private',endpoint_template:'/{series}/events'},{strategy:'series-events-v1',external_id:'future-series',endpoint_template:'https://evil.example/events'},{strategy:'series-events-v1',external_id:'future-series',endpoint_template:'/../events'},{strategy:'season-rallies-v1',external_id:'wrc',endpoint_template:'/{series}/events'},{strategy:'series-events-v1',external_id:'',endpoint_template:'/{series}/events'},{strategy:'series-events-v1',external_id:'future-series',endpoint_template:'/{series}/events',api_key:'secret'}])('rejects unsafe OCBlackTop manual source %#',value=>{expect(()=>new OcBlackTopAdapter().validateSourceConfig(value,{providerConfig:{base_url:'https://api.ocblacktop.com/v1'}})).toThrow();});
  it('tests OCBlackTop through a documented series endpoint, never an assumed global endpoint',async()=>{let called='';const adapter=new OcBlackTopAdapter(async input=>{called=String(input);return response({data:[]});},[{externalId:'formula1',name:'Formula 1',strategy:'series-events-v1',endpointTemplate:'/{series}/events'}]);const ctx=context('https://api.ocblacktop.com/v1');await adapter.testConnection(ctx);expect(called).toContain('/formula1/events');expect(called).not.toContain('/sports');expect(ctx.requestCounter.value).toBe(1);});
  it.each([[false,'partial'],[true,'complete']] as const)('marks TheSportsDB discovery as %s only when configured safely',(complete)=>{return (async()=>{let calledUrl='',calledHeaders:HeadersInit|undefined;const adapter=new TheSportsDbAdapter(async(input,init)=>{calledUrl=String(input);calledHeaders=init?.headers;return response({leagues:[{idLeague:'4454',strLeague:'WorldSBK',strSport:'Motorsport'},{idLeague:'1',strLeague:'Football',strSport:'Soccer'}]});});const ctx=context('https://www.thesportsdb.com/api/v1/json','test-key',complete);const result=await adapter.discoverChampionships(ctx);expect(result.complete).toBe(complete);expect(result.items.map(item=>item.name)).toEqual(['WorldSBK']);expect(result.items[0]?.sourceConfig.strategy).toBe('league-season-v1');expect(calledUrl).toContain('/api/v1/json/test-key/all_leagues.php');expect(calledHeaders).toEqual({accept:'application/json'});expect(ctx.requestCounter.value).toBe(1);})();});
  it('accepts only the implemented TheSportsDB v1 source strategy',()=>{const adapter=new TheSportsDbAdapter();expect(adapter.validateSourceConfig({strategy:'league-season-v1',external_id:'4380'})).toEqual({strategy:'league-season-v1',external_id:'4380'});expect(()=>adapter.validateSourceConfig({strategy:'league-season-v2',external_id:'4380'})).toThrow(/league-season-v1/);expect(()=>adapter.validateSourceConfig({strategy:'future-strategy',external_id:'4380'})).toThrow(/league-season-v1/);expect(()=>adapter.validateSourceConfig({strategy:'league-season-v1',external_id:'4380',endpoint_template:'/events'})).toThrow(/aucun modèle endpoint/);expect(()=>adapter.validateSourceConfig({strategy:'league-season-v1',external_id:'world-superbike'})).toThrow(/numérique/);});
  it.each([401,429,500])('counts one sent HTTP %s request exactly once',async status=>{const counter={value:0,increment(){this.value++;}};await expect(fetchProviderJson({url:new URL('https://api.ocblacktop.com/v1/formula1/events'),allowedHosts:['api.ocblacktop.com'],counter,fetchImpl:async()=>response({},status)})).rejects.toMatchObject({code:`http_${status}`});expect(counter.value).toBe(1);});
  it('counts a timed-out sent request exactly once',async()=>{const counter={value:0,increment(){this.value++;}};await expect(fetchProviderJson({url:new URL('https://api.ocblacktop.com/v1/formula1/events'),allowedHosts:['api.ocblacktop.com'],counter,timeoutMs:1,fetchImpl:async(_url,init)=>new Promise((_resolve,reject)=>init?.signal?.addEventListener('abort',()=>reject(new DOMException('aborted','AbortError'))))})).rejects.toMatchObject({code:'timeout'});expect(counter.value).toBe(1);});
  it('rejects unsafe endpoints without counting a request',async()=>{const counter={value:0,increment(){this.value++;}};await expect(fetchProviderJson({url:new URL('http://127.0.0.1/private'),allowedHosts:['api.ocblacktop.com'],counter})).rejects.toMatchObject({code:'unsafe_endpoint'});expect(counter.value).toBe(0);});
});
