import {describe,expect,it,vi} from 'vitest';
import type {ProviderRequestGate} from '../src/providers/contracts.js';
import {fetchProviderJson,ProviderHttpError} from '../src/providers/providerHttp.js';
import {StrictProviderRequestBudget} from '../src/providers/providerOneShotRunner.js';

function quota():ProviderRequestGate{return {beforeRequest:vi.fn(async()=>({allowed:true,chargeId:'charge'})),afterResponse:vi.fn(async()=>undefined),afterError:vi.fn(async()=>undefined)};}
const response=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{'content-type':'application/json'}});

describe('bounded one-shot provider request boundary',()=>{
  it('prevents request N+1 before the mocked HTTP implementation is called',async()=>{const delegate=quota(),budget=new StrictProviderRequestBudget(1,delegate),fetchImpl=vi.fn(async()=>response({ok:true}));const input={url:new URL('https://provider.fixture.test/page'),allowedHosts:['provider.fixture.test'],fetchImpl,gate:budget};await fetchProviderJson(input);await expect(fetchProviderJson(input)).rejects.toMatchObject({code:'request_budget_exhausted'});expect(fetchImpl).toHaveBeenCalledTimes(1);expect(budget.emitted).toBe(1);expect(budget.remaining).toBe(0);});
  it('counts an HTTP error attempt and never retries it automatically',async()=>{const budget=new StrictProviderRequestBudget(2,quota()),fetchImpl=vi.fn(async()=>response({error:'fixture'},503));await expect(fetchProviderJson({url:new URL('https://provider.fixture.test/failure'),allowedHosts:['provider.fixture.test'],fetchImpl,gate:budget})).rejects.toBeInstanceOf(ProviderHttpError);expect(fetchImpl).toHaveBeenCalledTimes(1);expect(budget.emitted).toBe(1);expect(budget.remaining).toBe(1);});
  it('permits exactly two attempts for a two-request budget and blocks the third',async()=>{const budget=new StrictProviderRequestBudget(2,quota()),fetchImpl=vi.fn(async()=>response({ok:true})),input={url:new URL('https://provider.fixture.test/page'),allowedHosts:['provider.fixture.test'],fetchImpl,gate:budget};await fetchProviderJson(input);await fetchProviderJson(input);await expect(fetchProviderJson(input)).rejects.toMatchObject({code:'request_budget_exhausted'});expect(fetchImpl).toHaveBeenCalledTimes(2);expect(budget.emitted).toBe(2);});
  it('a stopped runner cannot authorize another provider request',async()=>{const delegate=quota(),budget=new StrictProviderRequestBudget(2,delegate);budget.stop();expect(await budget.beforeRequest()).toEqual({allowed:false,reason:'request_cancelled'});expect(delegate.beforeRequest).not.toHaveBeenCalled();expect(budget.emitted).toBe(0);});
  it('serially reserves the strict ceiling even when authorization is concurrent',async()=>{let release!:()=>void;const waiting=new Promise<void>(resolve=>{release=resolve;});const delegate=quota();delegate.beforeRequest=vi.fn(async()=>{await waiting;return {allowed:true,chargeId:'charge'};});const budget=new StrictProviderRequestBudget(1,delegate);const first=budget.beforeRequest();const second=budget.beforeRequest();expect(await second).toEqual({allowed:false,reason:'request_budget_exhausted'});release();expect((await first).allowed).toBe(true);expect(budget.emitted).toBe(1);});
  it('rejects an absent, zero, negative or non-integral budget',()=>{for(const value of [0,-1,1.5,Number.NaN])expect(()=>new StrictProviderRequestBudget(value,quota())).toThrow('max_provider_requests_invalid');});
});
