import {describe,expect,it,vi} from 'vitest';
import {fetchProviderJson,ProviderHttpError} from '../src/providers/providerHttp.js';

describe('Lot 5.5 provider HTTP quota gate',()=>{
  it('rejects locally before charging an unsafe endpoint',async()=>{const before=vi.fn();await expect(fetchProviderJson({url:new URL('http://127.0.0.1/private'),allowedHosts:['127.0.0.1'],gate:{beforeRequest:before,afterResponse:vi.fn(),afterError:vi.fn()}})).rejects.toMatchObject({code:'unsafe_endpoint'});expect(before).not.toHaveBeenCalled();});
  it('does not emit and preserves quota deferral details when the gate refuses',async()=>{const transport=vi.fn();await expect(fetchProviderJson({url:new URL('https://provider.test/data'),allowedHosts:['provider.test'],fetchImpl:transport,gate:{beforeRequest:async()=>({allowed:false,reason:'quota_month',nextEligibleAt:'2026-08-15T00:00:00.000Z'}),afterResponse:vi.fn(),afterError:vi.fn()}})).rejects.toMatchObject({code:'quota_deferred',reason:'quota_month',nextEligibleAt:'2026-08-15T00:00:00.000Z'});expect(transport).not.toHaveBeenCalled();});
  it('charges once and records normalized response metadata',async()=>{const after=vi.fn(),transport=vi.fn().mockResolvedValue(new Response('{"ok":true}',{status:200,headers:{'content-type':'application/json','x-rate-limit-remaining':'4'}}));await expect(fetchProviderJson({url:new URL('https://provider.test/data'),allowedHosts:['provider.test'],fetchImpl:transport,gate:{beforeRequest:async()=>({allowed:true,chargeId:'charge-1'}),afterResponse:after,afterError:vi.fn()}})).resolves.toEqual({ok:true});expect(transport).toHaveBeenCalledOnce();expect(after).toHaveBeenCalledWith('charge-1',expect.objectContaining({status:200}));});
  it('keeps the charge on a transport timeout after authorization',async()=>{const failed=vi.fn(),transport=vi.fn().mockRejectedValue(new DOMException('aborted','AbortError'));await expect(fetchProviderJson({url:new URL('https://provider.test/data'),allowedHosts:['provider.test'],fetchImpl:transport,gate:{beforeRequest:async()=>({allowed:true,chargeId:'charge-2'}),afterResponse:vi.fn(),afterError:failed}})).rejects.toEqual(expect.any(ProviderHttpError));expect(failed).toHaveBeenCalledWith('charge-2',expect.objectContaining({code:'timeout'}));});
});
