import {createHmac,randomBytes,randomUUID,timingSafeEqual} from 'node:crypto';
import type {Pool,PoolClient} from 'pg';
import {pool,withTransaction} from '../lib/db.js';

export const previewScopes=['championships:read','events:read','meetings:read','changes:read'] as const;
export type PreviewScope=typeof previewScopes[number];
export type ApiClientPrincipal={clientId:string;keyId:string;scopes:Set<PreviewScope>;championshipIds:Set<string>;rateLimit:number;dailyQuota:number;pageLimit:number;changesPageLimit:number};
type Queryable=Pick<Pool,'query'>|Pick<PoolClient,'query'>;

const digest=(key:string,pepper:string)=>createHmac('sha256',pepper).update(key).digest('hex');
const utcMinute=(now:Date)=>new Date(Math.floor(now.valueOf()/60000)*60000);
const utcDay=(now:Date)=>now.toISOString().slice(0,10);
export function constantTimeDigestEqual(left:string,right:string){const a=Buffer.from(left,'hex'),b=Buffer.from(right,'hex');return a.length===b.length&&timingSafeEqual(a,b);}

export class PreviewClientSecurityService{
  constructor(private readonly pepper:string,private readonly db:Queryable=pool,private readonly transaction=withTransaction){if(pepper.length<32)throw new Error('PREVIEW_API_KEY_PEPPER must contain at least 32 characters');}
  async createClient(input:{name:string;scopes:PreviewScope[];championshipIds:string[];rateLimit?:number;dailyQuota?:number;pageLimit?:number;changesPageLimit?:number}){const id=randomUUID(),scopes=[...new Set(input.scopes)],championships=[...new Set(input.championshipIds)];await this.transaction(async client=>{await client.query(`insert into api_clients(id,name,rate_limit_per_minute,daily_quota,page_limit,changes_page_limit) values($1,$2,$3,$4,$5,$6)`,[id,input.name,input.rateLimit??60,input.dailyQuota??10000,input.pageLimit??100,input.changesPageLimit??500]);for(const scope of scopes)await client.query('insert into api_client_scopes(client_id,scope) values($1,$2)',[id,scope]);for(const championship of championships)await client.query('insert into api_client_championships(client_id,championship_id) values($1,$2)',[id,championship]);});return {id,name:input.name,status:'active',rate_limit_per_minute:input.rateLimit??60,daily_quota:input.dailyQuota??10000,page_limit:input.pageLimit??100,changes_page_limit:input.changesPageLimit??500,scopes,championship_ids:championships};}
  async createKey(clientId:string,environment:'live'|'test',name:string){const id=randomUUID(),prefix=randomBytes(9).toString('base64url'),secret=randomBytes(32).toString('base64url'),key=`mse_${environment}_${prefix}_${secret}`;const result=await this.db.query(`insert into api_keys(id,client_id,environment,name,key_prefix,key_digest) select $1,id,$2,$3,$4,$5 from api_clients where id=$6 and status<>'closed' returning id`,[id,environment,name,prefix,digest(key,this.pepper),clientId]);if(!result.rowCount)throw new Error('api_client_not_found');return {id,client_id:clientId,environment,name,prefix,api_key:key};}
  async verify(key:string):Promise<ApiClientPrincipal|null>{const match=/^mse_(live|test)_([A-Za-z0-9_-]{12})_([A-Za-z0-9_-]{43})$/.exec(key);if(!match){constantTimeDigestEqual(digest(key,this.pepper),digest('invalid',this.pepper));return null;}const result=await this.db.query(`select k.id key_id,k.key_digest,c.id client_id,c.status,c.rate_limit_per_minute,c.daily_quota,c.page_limit,c.changes_page_limit,array_remove(array_agg(distinct s.scope),null) scopes,array_remove(array_agg(distinct e.championship_id),null) championships from api_keys k join api_clients c on c.id=k.client_id left join api_client_scopes s on s.client_id=c.id left join api_client_championships e on e.client_id=c.id where k.key_prefix=$1 and k.status='active' group by k.id,c.id`,[match[2]]);const row=result.rows[0],provided=digest(key,this.pepper),expected=String(row?.key_digest??digest('unknown-prefix',this.pepper)),valid=constantTimeDigestEqual(provided,expected);if(!row||!valid||row.status!=='active')return null;await this.db.query('update api_keys set last_used_at=now() where id=$1',[row.key_id]);return {clientId:String(row.client_id),keyId:String(row.key_id),scopes:new Set(row.scopes as PreviewScope[]),championshipIds:new Set((row.championships as string[]).map(String)),rateLimit:Number(row.rate_limit_per_minute),dailyQuota:Number(row.daily_quota),pageLimit:Number(row.page_limit),changesPageLimit:Number(row.changes_page_limit)};}
  async charge(principal:ApiClientPrincipal,now=new Date()){return this.transaction(async client=>{const minute=utcMinute(now),day=utcDay(now);const rate=await client.query(`insert into api_client_minute_usage(client_id,minute_start,request_count) values($1,$2,1) on conflict(client_id,minute_start) do update set request_count=api_client_minute_usage.request_count+1 where api_client_minute_usage.request_count<$3 returning request_count`,[principal.clientId,minute,principal.rateLimit]);if(!rate.rowCount){const daily=await client.query('select coalesce((select request_count from api_client_daily_usage where client_id=$1 and usage_day=$2),0)::text request_count',[principal.clientId,day]);return {allowed:false,code:'rate_limit_exceeded' as const,retryAfter:Math.max(1,60-now.getUTCSeconds()),minuteRemaining:0,dailyRemaining:principal.dailyQuota-Number(daily.rows[0].request_count)};}const daily=await client.query(`insert into api_client_daily_usage(client_id,usage_day,request_count) values($1,$2,1) on conflict(client_id,usage_day) do update set request_count=api_client_daily_usage.request_count+1 where api_client_daily_usage.request_count<$3 returning request_count`,[principal.clientId,day,principal.dailyQuota]);if(!daily.rowCount){await client.query('update api_client_minute_usage set request_count=request_count-1 where client_id=$1 and minute_start=$2',[principal.clientId,minute]);return {allowed:false,code:'daily_quota_exceeded' as const,retryAfter:Math.max(1,Math.ceil((Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),now.getUTCDate()+1)-now.valueOf())/1000)),minuteRemaining:principal.rateLimit-Number(rate.rows[0].request_count)+1,dailyRemaining:0};}return {allowed:true as const,minute,day,minuteRemaining:principal.rateLimit-Number(rate.rows[0].request_count),dailyRemaining:principal.dailyQuota-Number(daily.rows[0].request_count),retryAfter:Math.max(1,60-now.getUTCSeconds())};});}
  async refundDaily(clientId:string,day:string|undefined){if(day)await this.db.query('update api_client_daily_usage set request_count=greatest(0,request_count-1) where client_id=$1 and usage_day=$2',[clientId,day]);}
  async setStatus(id:string,status:'active'|'suspended'){const result=await this.db.query('update api_clients set status=$2,updated_at=now() where id=$1 and status<>\'closed\' returning id,name,status,rate_limit_per_minute,daily_quota,page_limit,changes_page_limit',[id,status]);return result.rows[0]??null;}
  async revokeKey(id:string){const result=await this.db.query(`update api_keys set status='revoked',revoked_at=now() where id=$1 and status='active' returning id,client_id,name,key_prefix prefix,status,revoked_at`,[id]);return result.rows[0]??null;}
  async replaceRights(id:string,input:{scopes:PreviewScope[];championshipIds:string[];rateLimit:number;dailyQuota:number;pageLimit:number;changesPageLimit:number}){return this.transaction(async client=>{await client.query('update api_clients set rate_limit_per_minute=$2,daily_quota=$3,page_limit=$4,changes_page_limit=$5,updated_at=now() where id=$1',[id,input.rateLimit,input.dailyQuota,input.pageLimit,input.changesPageLimit]);await client.query('delete from api_client_scopes where client_id=$1',[id]);await client.query('delete from api_client_championships where client_id=$1',[id]);for(const scope of [...new Set(input.scopes)])await client.query('insert into api_client_scopes(client_id,scope) values($1,$2)',[id,scope]);for(const championship of [...new Set(input.championshipIds)])await client.query('insert into api_client_championships(client_id,championship_id) values($1,$2)',[id,championship]);return {id,scopes:[...new Set(input.scopes)],championship_ids:[...new Set(input.championshipIds)],rate_limit_per_minute:input.rateLimit,daily_quota:input.dailyQuota,page_limit:input.pageLimit,changes_page_limit:input.changesPageLimit};});}
}
