import { useEffect, useState } from 'react';
import { Navigate, Outlet, Route, Routes, useLocation } from 'react-router-dom';
import { AppShell, EmptyState as Empty, PageHeader, Panel, PLACEHOLDER_NAVIGATION_ITEMS, QualityBar as Quality, StatusChip as Pill } from './design-system';
import type { Tone } from './design-system';
import { ChampionshipsPage } from './pages/ChampionshipsPage';
import { EventsPage } from './pages/EventsPage';
import { CorrectionsPage } from './pages/CorrectionsPage';
import { assetRegistry } from './assets/assetRegistry';
import { AuthProvider, useAdminAuth } from './lib/adminAuth';
import { AuthenticationLoading, LoginPage } from './pages/LoginPage';
import { ProviderAcquisitionPage } from './features/provider-acquisition/ProviderAcquisitionPage';
import { SourcesPage } from './features/provider-sources/SourcesPage';

const API = import.meta.env.VITE_API_URL ?? (import.meta.env.DEV ? 'http://localhost:3001' : '');
type Row = Record<string, any>;
async function get(path:string){const r=await fetch(API+path);if(!r.ok)throw new Error(await r.text());return r.json()}
const fmt=(v:string)=>v?new Intl.DateTimeFormat('fr-FR',{dateStyle:'short',timeStyle:'short'}).format(new Date(v)):'—';
const dashboardSessions = [
  { time:'14:00', championship:'FORMULE 1', slug:'formula-1', session:'Practice 1', circuit:'Silverstone Circuit', delay:'DANS 18 MIN' },
  { time:'16:30', championship:'MotoGP', slug:'motogp', session:'Qualifications', circuit:'TT Circuit Assen', delay:'AUJOURD’HUI' },
  { time:'19:00', championship:'WSBK', slug:'wsbk', session:'Race 1', circuit:'Autodromo di Most', delay:'AUJOURD’HUI' },
  { time:'22:15', championship:'Formule E', slug:'formula-e', session:'Course', circuit:'Berlin Tempelhof', delay:'AUJOURD’HUI' },
  { time:'09:15', championship:'WRC', slug:'wrc', session:'SS4', circuit:'Rally Finland', delay:'DEMAIN' },
  { time:'14:00', championship:'INDYCAR', slug:'indycar', session:'Practice 1', circuit:'Road America', delay:'DANS 2 JOURS' },
];

function ProtectedConsole(){const auth=useAdminAuth();const location=useLocation();if(auth.status==='loading')return <AuthenticationLoading/>;if(auth.status!=='authenticated')return <Navigate to="/login" replace state={{from:location.pathname+location.search}}/>;return <AppShell><Outlet/></AppShell>}
export function App(){return <AuthProvider><Routes>
<Route path="/login" element={<LoginPage/>}/><Route element={<ProtectedConsole/>}><Route path="/" element={<Dashboard/>}/><Route path="/events" element={<EventsPage/>}/><Route path="/championships" element={<ChampionshipsPage/>}/><Route path="/corrections" element={<CorrectionsPage/>}/><Route path="/sources" element={<SourcesPage/>}/><Route path="/synchronizations" element={<ProviderAcquisitionPage/>}/><Route path="/circuits" element={<Circuits/>}/>
{PLACEHOLDER_NAVIGATION_ITEMS.map(({path,label})=><Route key={path} path={path} element={<Placeholder title={label}/>}/>)}<Route path="*" element={<Navigate to="/"/>}/></Route></Routes></AuthProvider>}
function Dashboard(){const [d,setD]=useState<any>();useEffect(()=>{void get('/api/v1/dashboard/summary').then(setD)},[]);return <><PageHeader title="TABLEAU DE BORD" subtitle="Centre de supervision des sports mécaniques"/><div className="service-grid">{[['◎','API','23 ms','Réponse moyenne'],['◉','Base de données','27 ms','Temps de réponse'],['◷','Scheduler','4','Workers actifs'],['◌','Sauvegardes','02:15','Dernière sauvegarde'],['⌘','Version','8.1.0-alpha.2-lot.4.4','À jour']].map((x,i)=><article className="service-card" key={x[1]}><i>{x[0]}</i><div><h3>{x[1]}</h3><Pill text={i===4?'À JOUR':'OPÉRATIONNEL'}/><strong>{x[2]}</strong><span>{x[3]}</span></div></article>)}</div><div className="dashboard-layout"><div><Panel title="PROCHAINES SÉANCES (48 HEURES)" action={<button>Voir le calendrier complet</button>}><div className="timeline">{dashboardSessions.map((r,i)=>{const logo=assetRegistry.championship(r.slug);return <div className="timeline-row" key={r.time+r.championship}><b className={i<3?'hot':''}>{r.time}</b><strong className="timeline-championship"><img src={logo.src} alt={logo.alt}/><span>{r.championship}</span></strong><span>{r.session}</span><em>{r.circuit}</em><Pill text={r.delay} tone={i===0?'red':i<4?'amber':'blue'}/><i>›</i></div>})}</div></Panel><div className="triple"><Mini title="SYNCHRONISATIONS" rows={['Aujourd’hui 154','Cette semaine 943','Ce mois-ci 3 412']}/><Mini title="CORRECTIONS" rows={['Actives 14','En attente 3','Conflits 1']}/><Mini title="DOUBLONS" rows={['Total détectés 23','À traiter 4','Résolus 7']}/></div><Panel title="ACTIVITÉ RÉCENTE"><div className="activity">{['Synchronisation Formule 1 terminée avec succès','Nouvelle correction sur Silverstone Circuit','Sauvegarde automatique terminée','Synchronisation MotoGP terminée avec succès'].map((x,i)=><div><b>11:{42-i*3}:15</b><Pill text={i===1?'ADMIN':'OK'} tone={i===1?'blue':'green'}/><span>{x}</span></div>)}</div></Panel></div><aside className="right-rail"><Panel title="PROVIDERS"><Provider name="OC BlackTop" status="Opérationnel"/><Provider name="TheSportsDB" status="Opérationnel"/><Provider name="FIA API" status="Dégradé" tone="amber"/><Provider name="RSS Custom" status="Opérationnel"/></Panel><Panel title="ALERTES ACTIVES">{['Backup échoué','API FIA lente','3 doublons détectés','Quota API bientôt atteint'].map((x,i)=><div className="alert"><i>{i<3?'△':'ⓘ'}</i><span>{x}<small>Il y a {14+i*7} min</small></span><b>{i===2?3:1}</b></div>)}</Panel></aside></div><Panel title="RESSOURCES SYSTÈME"><div className="resources">{[['CPU','31%'],['RAM','57%'],['DISQUE','44%'],['PostgreSQL','27 ms'],['Redis','12 ms'],['Queue','12'],['Workers','4/8']].map(x=><div><span>{x[0]}</span><strong>{x[1]}</strong><i>▁▂▃▂▅▃▆</i></div>)}</div></Panel></>}
function Mini({title,rows}:{title:string,rows:string[]}){return <Panel title={title}>{rows.map(r=><div className="mini-row"><span>{r.split(' ').slice(0,-1).join(' ')}</span><b>{r.split(' ').at(-1)}</b></div>)}</Panel>}
function Provider({name,status,tone='green'}:{name:string,status:string,tone?:Tone}){return <div className="provider"><div className="provider-logo">◎</div><span><b>{name}</b><small><i className={tone}/> {status}</small></span><em>⌁⌁⌁</em><i>›</i></div>}

function Summary({title,rows}:{title:string,rows:string[]}){return <Panel title={title}><div className="summary">{rows.map(r=>{const a=r.split(' ');return <div><span>{a.slice(0,-1).join(' ')}</span><b>{a.at(-1)}</b></div>})}</div></Panel>}

function EventChip({label,day}:{label:string,day:number}){return <div className={'event-chip e'+(Math.abs(day)%7)}><b>{label}</b><span>{day%2?'Course':'Practice 1'}</span><small>{day%3?'🇩🇪':'🇮🇹'}</small></div>}

function Synchronizations(){return <><PageHeader title="SYNCHRONISATIONS" subtitle="Surveillez et contrôlez les synchronisations des données" action={<button className="danger">▷ Synchronisation globale</button>}/><div className="sync-layout"><div><div className="section-title"><h2>État des providers</h2><button>Actualisation auto. 30 secondes⌄</button></div><div className="providers-grid">{[['OC','OC BlackTop','342 / 1 200','71%','312 ms','green'],['TSDB','TheSportsDB','156 / 1 000','84%','284 ms','green'],['E','Ergast F1 API','98 / 600','83%','198 ms','green'],['FIA','FIA WRC API','45 / 300','15%','1 245 ms','amber']].map(x=><article className="provider-card"><header><i>{x[0]}</i><b>{x[1]}</b><Pill text={x[5]==='green'?'Opérationnel':'Dégradé'} tone={x[5] as Tone}/></header><p>Requêtes (1h) <strong>{x[2]}</strong></p><p>Quota restant <strong>{x[3]}</strong></p><div className="quota"><i style={{width:x[3]}}/></div><p>Temps de réponse <b>{x[4]}</b></p><p>Dernière vérification <strong>Il y a 1 min ✓</strong></p></article>)}</div><Panel title="Synchronisations en cours"><SyncTable/></Panel><Panel title="File d'attente des tâches"><SyncTable queue/></Panel></div><div><Panel title="Dernières exécutions">{['F1 - Saison 2026','MotoGP - Saison 2026','WSBK - Saison 2026','WRC - Saison 2026','IndyCar - Saison 2026'].map((x,i)=><div className={'execution '+(i===3?'failed':'')}><b>{x}</b><span>Durée : 2 min {34-i*5} s</span><Pill text={i===3?'Échec':'Réussie'} tone={i===3?'red':'green'}/></div>)}</Panel></div><aside><Summary title="RÉSUMÉ DES SYNCHRONISATIONS" rows={['Synchronisations réussies 27','Échecs 2','En cours 5','En attente 7','Durée totale 1h47','Volume de données 512Mo']}/><Panel title="PERFORMANCE (24h)"><div className="chart">╱╲__╱╲____╱╲<br/>__╱╲____╱╲___</div></Panel><Summary title="DERNIÈRES ERREURS" rows={['FIA WRC API Timeout','OC BlackTop Gateway','TheSportsDB Limite']}/><Summary title="ACTIONS RAPIDES" rows={['▷ Synchroniser un championnat','⌫ Vider la file d’attente','↻ Vérifier tous les providers','▤ Voir les journaux']}/></aside></div></>}
function SyncTable({queue=false}:{queue?:boolean}){return <table className="data-table"><thead><tr><th>{queue?'ORDRE':'CHAMPIONNAT'}</th><th>CHAMPIONNAT</th><th>PROVIDER</th><th>TÂCHE</th><th>{queue?'PLANIFIÉE POUR':'PROGRESSION'}</th><th>STATUT</th><th>ACTIONS</th></tr></thead><tbody>{['Formula 1','MotoGP','WSBK','WRC','IndyCar'].slice(0,queue?3:5).map((x,i)=><tr><td>{queue?i+1:x}</td><td><b>{x}</b></td><td>OC BlackTop</td><td>Saison 2026<small>Épreuves & sessions</small></td><td>{queue?'Aujourd’hui 12:'+(i*15).toString().padStart(2,'0'):<Quality value={[78,55,33,12,5][i]}/>}</td><td><Pill text={queue?'Normale':'En cours'} tone={queue?'muted':'blue'}/></td><td><button>□</button><button>•••</button></td></tr>)}</tbody></table>}
function Circuits(){return <><PageHeader title="CIRCUITS" subtitle="Catalogue et localisation des circuits"/><Placeholder title="Circuits — implémentation visuelle planifiée après Phase 1.1"/></>}
function Placeholder({title}:{title:string}){return <Panel title={title}><Empty text="Structure prête. Ce module sera développé à partir des fondations MEDS validées."/></Panel>}
