name: Rapport de bug serveur
description: Signaler un problème du serveur central
title: "[Bug] "
body:
  - type: input
    id: version
    attributes:
      label: Version du serveur
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Journaux
