import {adminAuthorization,notifyAuthenticationRequired} from '../../lib/adminAuth';
const API=import.meta.env.VITE_API_URL??(import.meta.env.DEV?'http://localhost:3001':'');
export type Provider={id:string;name:string;adapter_key:string;enabled:boolean;state:string;discovery_enabled:boolean;max_concurrency:number;config:Record<string,unknown>;secrets:Array<{name:string;configured:boolean}>;championship_count:number;updated_at:string};
export type ProviderChampionship={id:string;championship_id:string;championship_name:string;external_championship_id:string;sync_state:'inactive'|'active'|'paused';is_primary:boolean;source_config:Record<string,unknown>|null;current_stream_id:string|null};
export type QuotaPolicy={short_window_seconds:number|null;short_limit:number|null;minute_limit:number|null;hourly_limit:number|null;daily_limit:number|null;monthly_limit:number|null;limits_source:'configured'|'provider_headers'|'hybrid';reset_timezone:string|null;reset_at:string|null;minimum_interval_seconds:number;safety_margin_percent:number;current_reserve_mode:'percent'|'absolute';current_reserve_value:number;provider_timezone:string};
export type QuotaDiagnostics={policy:QuotaPolicy|null;runtime:Record<string,unknown>|null;windows:Record<string,unknown>[];observations:Record<string,unknown>[];summary:{limit:number|null;operational_ceiling:number|null;current_reserve:number|null;normal_budget:number|null;usage:number;remaining_estimated:number|null;distance_before_reserve:number|null;source:string;state:string;next_eligible_at:string|null;blocking_reason:string|null}};
export type SyncStream={id:string;phase:'current'|'historical';state:string;cursor:Record<string,unknown>|null;historical_state:Record<string,unknown>|null;last_progress_at:string|null;next_eligible_at:string|null;priority_boost_until:string|null;lease_owner:string|null;lease_expires_at:string|null;stream_backoff_until:string|null;stream_failure_count:number;last_error_code:string|null;season:number|null};
export type SyncRun={id:string;work_class:string;status:string;started_at:string;finished_at:string|null;requests_count:number;items_read:number;items_created:number;items_updated:number;items_unchanged:number;warnings_count:number;errors_count:number;error_summary:string|null};
async function request<T>(path:string,init:RequestInit={}):Promise<T>{const headers=new Headers(init.headers);if(init.body)headers.set('Content-Type','application/json');for(const[key,value]of Object.entries(adminAuthorization()))headers.set(key,value);const response=await fetch(API+path,{...init,headers,credentials:'include'});if(response.status===401){notifyAuthenticationRequired();throw new Error('Authentification requise.');}if(!response.ok){const body=await response.json().catch(()=>({})) as {message?:string};throw new Error(body.message??'Opération impossible.');}return response.json() as Promise<T>;}
export const listProviders=()=>request<Provider[]>('/api/v1/admin/providers');
export const createProvider=(value:unknown)=>request<Provider>('/api/v1/admin/providers',{method:'POST',body:JSON.stringify(value)});
export const updateProvider=(id:string,value:unknown)=>request<Provider>(`/api/v1/admin/providers/${id}`,{method:'PATCH',body:JSON.stringify(value)});
export const replaceCredential=(id:string,value:string)=>request<{secretConfigured:boolean}>(`/api/v1/admin/providers/${id}/secrets/api_key`,{method:'PUT',body:JSON.stringify({value})});
export const listChampionships=(id:string)=>request<ProviderChampionship[]>(`/api/v1/admin/providers/${id}/championships`);
export const createChampionship=(id:string,value:unknown)=>request(`/api/v1/admin/providers/${id}/championship-sources/manual`,{method:'POST',body:JSON.stringify(value)});
export const updateChampionship=(id:string,value:unknown)=>request(`/api/v1/admin/provider-championships/${id}`,{method:'PATCH',body:JSON.stringify(value)});
export const updateSourceConfig=(id:string,config:unknown)=>request(`/api/v1/admin/provider-championships/${id}/source-config`,{method:'PUT',body:JSON.stringify({config})});
export const quota=(id:string)=>request<QuotaPolicy>(`/api/v1/admin/providers/${id}/quota-policy`);
export function quotaMutationDto(value:QuotaPolicy):QuotaPolicy{return {short_window_seconds:value.short_window_seconds,short_limit:value.short_limit,monthly_limit:value.monthly_limit,limits_source:value.limits_source,reset_timezone:value.reset_timezone,reset_at:value.reset_at,minute_limit:value.minute_limit,hourly_limit:value.hourly_limit,daily_limit:value.daily_limit,minimum_interval_seconds:value.minimum_interval_seconds,safety_margin_percent:value.safety_margin_percent,current_reserve_mode:value.current_reserve_mode,current_reserve_value:value.current_reserve_value,provider_timezone:value.provider_timezone};}
export const saveQuota=(id:string,value:QuotaPolicy)=>request(`/api/v1/admin/providers/${id}/quota-policy`,{method:'PUT',body:JSON.stringify(quotaMutationDto(value))});
export const quotaDiagnostics=(id:string)=>request<QuotaDiagnostics>(`/api/v1/admin/providers/${id}/quota-diagnostics`);
export const syncStreams=(id:string)=>request<SyncStream[]>(`/api/v1/admin/provider-championships/${id}/sync-streams`);
export const syncRuns=(id:string)=>request<SyncRun[]>(`/api/v1/admin/provider-championships/${id}/sync-runs`);
export const mappings=(id:string)=>request<{active:any;versions:any[]}>(`/api/v1/admin/provider-championships/${id}/normalization-mappings`);
export const createMapping=(id:string,value:unknown)=>request(`/api/v1/admin/provider-championships/${id}/normalization-mappings`,{method:'POST',body:JSON.stringify(value)});
export const preflight=(id:string)=>request<Record<string,unknown>>(`/api/v1/admin/provider-championships/${id}/preflight`,{method:'POST',body:JSON.stringify({max_provider_requests:1})});
