import {describe,expect,it} from 'vitest';
import {renderToStaticMarkup} from 'react-dom/server';
import {adapterLabel,emptyProviderListSummary,forbiddenSourcesActions,mappingPrimaryExperience,parseLocalizedNumber,providerDetailTabs,providerListSummary,quotaFormFields,quotaSubmission,readinessPresentation,resolveSelectedChampionship,safeJson,SourcesPage,validateQuotaNumberInput} from './SourcesPage';
import type {ProviderChampionship,QuotaDiagnostics,SyncRun,SyncStream} from './sourcesApi';

const association=(id:string,name:string):ProviderChampionship=>({id,championship_id:id,championship_name:name,external_championship_id:`external-${id}`,sync_state:'inactive',is_primary:false,source_config:{strategy:`strategy-${id}`},current_stream_id:null});
const diagnostics:QuotaDiagnostics={policy:{short_window_seconds:null,short_limit:null,minute_limit:60,hourly_limit:null,daily_limit:null,monthly_limit:1000,limits_source:'configured',reset_timezone:null,reset_at:'2026-09-01T00:00:00Z',minimum_interval_seconds:1,safety_margin_percent:5,current_reserve_mode:'percent',current_reserve_value:20,provider_timezone:'UTC'},runtime:null,windows:[],observations:[],summary:{limit:1000,operational_ceiling:950,current_reserve:190,normal_budget:760,usage:100,remaining_estimated:850,distance_before_reserve:660,source:'local_counter',state:'normal',next_eligible_at:'2026-08-27T10:00:00Z',blocking_reason:'dynamic_pacing'}};
const stream:SyncStream={id:'stream',phase:'current',state:'ready',cursor:null,historical_state:null,last_progress_at:null,next_eligible_at:'2026-08-27T10:00:00Z',priority_boost_until:null,lease_owner:null,lease_expires_at:null,stream_backoff_until:null,stream_failure_count:0,last_error_code:null,season:2026};
const run:SyncRun={id:'run',work_class:'current',status:'completed',started_at:'2026-08-26T09:00:00Z',finished_at:'2026-08-26T09:01:00Z',requests_count:1,items_read:2,items_created:1,items_updated:0,items_unchanged:1,warnings_count:0,errors_count:0,error_summary:null};

describe('Sources page contract',()=>{
  it('renders the existing Sources shell and a loading state without a real-run action',()=>{const html=renderToStaticMarkup(<SourcesPage/>);expect(html).toContain('SOURCES');expect(html).toContain('Chargement');expect(html).not.toMatch(/Synchroniser maintenant|Tester OCBlackTop|Run now|Importer/);});
  it('never renders a credential value in its initial state',()=>{const html=renderToStaticMarkup(<SourcesPage/>);expect(html).not.toContain('SYNTHETIC_NOT_REAL');expect(html).not.toMatch(/ciphertext|nonce|masterKey/);});
  it('selects each provider championship explicitly and preserves a still-existing selection',()=>{const links=[association('f1','Formule 1'),association('formula-e','Formula E')];expect(resolveSelectedChampionship(links,null)?.id).toBe('f1');expect(resolveSelectedChampionship(links,'formula-e')?.source_config?.strategy).toBe('strategy-formula-e');expect(resolveSelectedChampionship(links,'missing')?.id).toBe('f1');});
  it('resets naturally to the new provider first association',()=>{expect(resolveSelectedChampionship([association('moto-e','Moto E')],null)?.id).toBe('moto-e');expect(resolveSelectedChampionship([],null)).toBeNull();});
  it('handles invalid quota or mapping JSON without throwing',()=>{expect(safeJson('{invalid')).toEqual({ok:false,message:'Le JSON saisi est invalide.'});expect(safeJson('[]').ok).toBe(false);expect(safeJson('{"ok":true}')).toEqual({ok:true,value:{ok:true}});});
  it('defines no operational or real-run action in Sources',()=>{const source=SourcesPage.toString();for(const action of forbiddenSourcesActions)expect(source).not.toContain(`>${action}<`);expect(source).not.toContain('updateSyncState');});
  it('structure le détail fournisseur selon le contrat validé',()=>{expect(providerDetailTabs).toEqual(['Vue d’ensemble','Configuration','Quotas','Championnats','Synchronisation','Historique & logs']);});
  it('administre les quotas avec des champs métier sans JSON obligatoire',()=>{expect(quotaFormFields).toContain('monthly_limit');expect(quotaFormFields).toContain('safety_margin_percent');expect(quotaFormFields).toContain('current_reserve_value');});
  it('convertit strictement les nombres français avant la requête quota',()=>{expect(parseLocalizedNumber('5,00')).toEqual({ok:true,value:5});expect(parseLocalizedNumber('5.00')).toEqual({ok:true,value:5});expect(parseLocalizedNumber('5.5')).toEqual({ok:true,value:5.5});expect(parseLocalizedNumber('')).toEqual({ok:true,value:null});});
  it('refuse les nombres ambigus ou invalides au lieu de produire NaN',()=>{expect(parseLocalizedNumber('5,0.0')).toMatchObject({ok:false});expect(parseLocalizedNumber('1 000,5')).toMatchObject({ok:false});expect(parseLocalizedNumber('abc')).toMatchObject({ok:false});});
  it('ne construit aucune soumission tant qu’un champ quota est invalide',()=>{expect(quotaSubmission(diagnostics.policy!,new Set(['safety_margin_percent']))).toBeNull();expect(quotaSubmission(diagnostics.policy!,new Set())).toBe(diagnostics.policy);});
  it('applique les bornes 0..20 à la marge de sécurité sans écraser la valeur valide',()=>{expect(validateQuotaNumberInput('0',5,0,20)).toEqual({valid:true,value:0});expect(validateQuotaNumberInput('20',5,0,20)).toEqual({valid:true,value:20});expect(validateQuotaNumberInput('-0,01',5,0,20)).toMatchObject({valid:false,value:5});expect(validateQuotaNumberInput('20.01',5,0,20)).toMatchObject({valid:false,value:5});});
  it('applique les bornes 0..50 à la réserve en pourcentage',()=>{expect(validateQuotaNumberInput('0',20,0,50)).toEqual({valid:true,value:0});expect(validateQuotaNumberInput('50',20,0,50)).toEqual({valid:true,value:50});expect(validateQuotaNumberInput('50,1',20,0,50)).toMatchObject({valid:false,value:20});});
  it('refuse une limite négative avec min=0 et conserve la dernière valeur valide',()=>{expect(validateQuotaNumberInput('-1',60,0)).toMatchObject({valid:false,value:60});expect(validateQuotaNumberInput('0',60,0)).toEqual({valid:true,value:0});});
  it('rend la soumission à nouveau possible après correction du champ invalide',()=>{const invalidFields=new Set<string>();const invalid=validateQuotaNumberInput('21',5,0,20);if(!invalid.valid)invalidFields.add('safety_margin_percent');expect(quotaSubmission(diagnostics.policy!,invalidFields)).toBeNull();const corrected=validateQuotaNumberInput('5,00',invalid.value,0,20);if(corrected.valid)invalidFields.delete('safety_margin_percent');expect(corrected).toEqual({valid:true,value:5});expect(quotaSubmission({...diagnostics.policy!,safety_margin_percent:corrected.value!},invalidFields)).toMatchObject({safety_margin_percent:5});});
  it('réserve le mapping JSON au mode avancé',()=>{expect(mappingPrimaryExperience).toEqual({mode:'summary',advancedLabel:'Paramètres avancés du mapping',unresolvedLabel:'À associer'});});
  it('résume quota, reset, cadence, éligibilité et dernière synchronisation depuis les APIs existantes',()=>{const summary=providerListSummary(diagnostics,[stream],[run]);expect(summary).toMatchObject({quotaState:'normal',quotaRemaining:'850',nextAction:'dynamic_pacing',alerts:'Aucune alerte'});expect(summary.nextReset).not.toBe('Non déterminé');expect(summary.nextEligibility).not.toBe('Non déterminée');expect(summary.lastSync).not.toBe('Aucune donnée');});
  it('présente des états neutres sans inventer de donnée',()=>{expect(providerListSummary(null,[],[])).toEqual(emptyProviderListSummary);});
  it('affiche un libellé adaptateur compréhensible',()=>{expect(adapterLabel('ocblacktop')).toBe('OCBlackTop');expect(adapterLabel('thesportsdb')).toBe('TheSportsDB');});
  it('sépare toujours credential et connexion API non vérifiée',()=>{const source=SourcesPage.toString();expect(source).toContain('Connexion API');expect(source).toContain('Non vérifiée');expect(source).not.toMatch(/Connexion API.{0,80}Credential configuré/);});
  it('le preflight ne peut pas transformer la connexion en OK',()=>{expect(readinessPresentation({configuration_ready:true,execution_ready:true,PROVIDER_CALLS:0})).toEqual({configurationReady:true,executionReady:true,blockers:[]});expect(SourcesPage.toString()).not.toContain('Connexion API : OK');});
  it('presents a paused but configured source as ready and execution as non-authorized',()=>{expect(readinessPresentation({configuration_ready:true,execution_ready:false,execution_blockers:['provider_disabled','provider_paused','championship_inactive'],PROVIDER_CALLS:0})).toEqual({configurationReady:true,executionReady:false,blockers:['Provider désactivé','Provider en pause','Championnat inactif']});});
  it('presents structural configuration failures separately',()=>{expect(readinessPresentation({configuration_ready:false,execution_ready:false,execution_blockers:['configuration_not_ready']})).toEqual({configurationReady:false,executionReady:false,blockers:['Configuration technique incomplète']});});
});
