import type {PoolClient} from 'pg';
import type {FieldClass,ResourceKind} from './deterministicReconciliation.js';

type Definition={class:FieldClass;nullable:boolean;kind:'string'|'timestamp'|'uuid'|'status'|'sessionType';max?:number;override:boolean;policy:boolean};
export const reconciliationFieldContract:Readonly<Record<ResourceKind,Readonly<Record<string,Definition>>>>={
  meeting:{name:{class:'DISPLAY',nullable:false,kind:'string',max:255,override:true,policy:true},round:{class:'DISPLAY',nullable:true,kind:'string',max:128,override:true,policy:true},startsAt:{class:'SCHEDULE',nullable:false,kind:'timestamp',override:true,policy:true},endsAt:{class:'SCHEDULE',nullable:true,kind:'timestamp',override:true,policy:true},venueId:{class:'REFERENCE',nullable:true,kind:'uuid',override:true,policy:true},venueLayoutId:{class:'REFERENCE',nullable:true,kind:'uuid',override:true,policy:true}},
  event:{name:{class:'DISPLAY',nullable:false,kind:'string',max:255,override:true,policy:true},sessionLabel:{class:'DISPLAY',nullable:true,kind:'string',max:255,override:true,policy:true},sessionType:{class:'REFERENCE',nullable:false,kind:'sessionType',max:128,override:true,policy:true},startsAt:{class:'SCHEDULE',nullable:false,kind:'timestamp',override:true,policy:true},endsAt:{class:'SCHEDULE',nullable:true,kind:'timestamp',override:true,policy:true},status:{class:'STATUS',nullable:false,kind:'status',override:true,policy:true},venueId:{class:'REFERENCE',nullable:true,kind:'uuid',override:true,policy:true},venueLayoutId:{class:'REFERENCE',nullable:true,kind:'uuid',override:true,policy:true}}
};
export class ReconciliationFieldValidationError extends Error{}
export const fieldDefinition=(kind:ResourceKind,field:string)=>reconciliationFieldContract[kind][field]??null;
export function validatePolicyField(kind:ResourceKind,field:string,fieldClass:FieldClass){const definition=fieldDefinition(kind,field);if(!definition?.policy)throw new ReconciliationFieldValidationError('field_not_reconcilable');if(definition.class!==fieldClass)throw new ReconciliationFieldValidationError('field_class_mismatch');return definition;}
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
export function normalizeFieldValue(kind:ResourceKind,field:string,value:unknown){const definition=fieldDefinition(kind,field);if(!definition?.override)throw new ReconciliationFieldValidationError('field_not_reconcilable');if(value===null){if(!definition.nullable)throw new ReconciliationFieldValidationError('field_null_forbidden');return null;}if(definition.kind==='string'){if(typeof value!=='string'||value.trim()===''||value.length>(definition.max??255))throw new ReconciliationFieldValidationError('field_string_invalid');return value;}if(definition.kind==='timestamp'){if(typeof value!=='string'||!Number.isFinite(Date.parse(value)))throw new ReconciliationFieldValidationError('field_timestamp_invalid');return new Date(value).toISOString();}if(definition.kind==='uuid'){if(typeof value!=='string'||!uuid.test(value))throw new ReconciliationFieldValidationError('field_uuid_invalid');return value;}if(definition.kind==='status'){if(typeof value!=='string'||!['draft','scheduled','completed','cancelled','postponed'].includes(value))throw new ReconciliationFieldValidationError('field_status_invalid');return value;}if(typeof value!=='string'||value.trim()===''||value.length>(definition.max??128))throw new ReconciliationFieldValidationError('field_session_type_invalid');return value;}
export async function validateFieldReferences(client:PoolClient,kind:ResourceKind,entityUuid:string,field:string,value:unknown){if(value===null||!['venueId','venueLayoutId','sessionType'].includes(field))return;if(field==='venueId'&&!(await client.query('select 1 from venues where id=$1',[value])).rowCount)throw new ReconciliationFieldValidationError('venue_not_found');if(field==='sessionType'&&!(await client.query('select 1 from session_types where key=$1 and active=true',[value])).rowCount)throw new ReconciliationFieldValidationError('session_type_not_found');if(field==='venueLayoutId'){const table=kind==='meeting'?'meetings':'events',identity=kind==='meeting'?'id':'normalized_uuid';const current=(await client.query(`select venue_id from ${table} where ${identity}=$1`,[entityUuid])).rows[0];const active=(await client.query(`select override_value#>>'{}' venue_id from canonical_field_overrides where entity_kind=$1 and entity_uuid=$2 and field_name='venueId' and status='active'`,[kind,entityUuid])).rows[0];const venueId=active?.venue_id??current?.venue_id??null;if(!(await client.query('select 1 from venue_layouts where id=$1 and venue_id=$2',[value,venueId])).rowCount)throw new ReconciliationFieldValidationError('venue_layout_scope_invalid');}}
