import type {FastifyInstance,FastifyReply,FastifyRequest} from 'fastify';
import {createHash} from 'node:crypto';
import {z} from 'zod';
import {previewReadRoutes} from './previewRead.js';
import {PreviewClientSecurityService,previewScopes,type ApiClientPrincipal} from '../preview/clientSecurity.js';
import type {PreviewRepository} from '../preview/repository.js';

const principals=new WeakMap<FastifyRequest,ApiClientPrincipal>(),charges=new WeakMap<FastifyRequest,{clientId:string;day:string|undefined}>();
export const previewPrincipal=(request:FastifyRequest)=>principals.get(request);
const clientError=(reply:FastifyReply,request:FastifyRequest,status:number,code:string,message:string)=>reply.code(status).send({error:{code,message,request_id:request.id}});
const requiredScope=(path:string)=>path.endsWith('/changes')?'changes:read':path.includes('/championships')?'championships:read':path.includes('/meetings')?'meetings:read':'events:read';

export async function previewSecurityRoutes(app:FastifyInstance,options:{security:PreviewClientSecurityService;cursorSecret:string;repository?:PreviewRepository;now?:()=>Date}){const now=options.now??(()=>new Date());
  app.addHook('onRequest',async(request,reply)=>{const authorization=request.headers.authorization,key=authorization?.startsWith('Bearer ')?authorization.slice(7).trim():'';const principal=await options.security.verify(key);if(!principal)return clientError(reply,request,401,'invalid_api_key','Valid Bearer API key required.');principals.set(request,principal);if(!principal.scopes.has(requiredScope(request.url.split('?',1)[0]??'') as any))return clientError(reply,request,403,'insufficient_scope','Required read scope is missing.');const charge=await options.security.charge(principal,now());reply.header('RateLimit-Limit',principal.rateLimit).header('RateLimit-Remaining',charge.minuteRemaining).header('RateLimit-Reset',charge.retryAfter).header('X-DailyLimit-Limit',principal.dailyQuota).header('X-DailyLimit-Remaining',charge.dailyRemaining).header('X-Request-Id',request.id);if(!charge.allowed){await reply.header('Retry-After',charge.retryAfter).code(429).send({error:{code:charge.code,message:charge.code==='rate_limit_exceeded'?'Per-minute rate limit exceeded.':'Daily quota exceeded.',request_id:request.id}});return;}charges.set(request,{clientId:principal.clientId,day:charge.day});});
  app.addHook('onSend',async(request,reply,payload)=>{const charge=charges.get(request);if(charge&&reply.statusCode>=500)await options.security.refundDaily(charge.clientId,charge.day);if(reply.statusCode===200&&request.method==='GET'&&typeof payload==='string'){const etag=`"${createHash('sha256').update(payload).digest('base64url')}"`;reply.header('ETag',etag);if(request.headers['if-none-match']===etag){reply.code(304);return '';} }return payload;});
  await app.register(previewReadRoutes,{repository:options.repository,cursorSecret:options.cursorSecret,now,principal:previewPrincipal});
}

const uuid=z.string().uuid(),championshipId=z.string().trim().min(1).max(160).regex(/^[A-Za-z0-9]+(?:[._:-][A-Za-z0-9]+)*$/),scope=z.enum(previewScopes),limits={rate_limit_per_minute:z.number().int().min(1).max(100000).default(60),daily_quota:z.number().int().min(1).max(100000000).default(10000),page_limit:z.number().int().min(1).max(100).default(100),changes_page_limit:z.number().int().min(1).max(500).default(500)};
export async function previewClientAdminRoutes(app:FastifyInstance,options:{security:PreviewClientSecurityService}){const service=options.security;
  app.post('/api/v1/admin/api-clients',async(request,reply)=>{const body=z.object({name:z.string().trim().min(1).max(160),scopes:z.array(scope).default([]),championship_ids:z.array(championshipId).default([]),...limits}).strict().safeParse(request.body);if(!body.success)return reply.code(400).send({message:'Client API invalide.'});return reply.code(201).send(await service.createClient({name:body.data.name,scopes:body.data.scopes,championshipIds:body.data.championship_ids,rateLimit:body.data.rate_limit_per_minute,dailyQuota:body.data.daily_quota,pageLimit:body.data.page_limit,changesPageLimit:body.data.changes_page_limit}));});
  app.post('/api/v1/admin/api-clients/:id/keys',async(request,reply)=>{const params=z.object({id:uuid}).safeParse(request.params),body=z.object({environment:z.enum(['live','test']),name:z.string().trim().min(1).max(160)}).strict().safeParse(request.body);if(!params.success||!body.success)return reply.code(400).send({message:'Clé API invalide.'});return reply.code(201).send(await service.createKey(params.data.id,body.data.environment,body.data.name));});
  app.post('/api/v1/admin/api-clients/:id/status',async(request,reply)=>{const params=z.object({id:uuid}).safeParse(request.params),body=z.object({status:z.enum(['active','suspended'])}).strict().safeParse(request.body);if(!params.success||!body.success)return reply.code(400).send({message:'État client invalide.'});return await service.setStatus(params.data.id,body.data.status)??reply.code(404).send({message:'Client introuvable.'});});
  app.post('/api/v1/admin/api-keys/:id/revoke',async(request,reply)=>{const parsed=uuid.safeParse((request.params as {id?:unknown}).id);if(!parsed.success)return reply.code(400).send({message:'Identifiant invalide.'});return await service.revokeKey(parsed.data)??reply.code(404).send({message:'Clé introuvable.'});});
  app.put('/api/v1/admin/api-clients/:id/rights',async(request,reply)=>{const params=z.object({id:uuid}).safeParse(request.params),body=z.object({scopes:z.array(scope),championship_ids:z.array(championshipId),...limits}).strict().safeParse(request.body);if(!params.success||!body.success)return reply.code(400).send({message:'Droits client invalides.'});return service.replaceRights(params.data.id,{scopes:body.data.scopes,championshipIds:body.data.championship_ids,rateLimit:body.data.rate_limit_per_minute,dailyQuota:body.data.daily_quota,pageLimit:body.data.page_limit,changesPageLimit:body.data.changes_page_limit});});
}
