import type {FastifyInstance,FastifyRequest} from 'fastify';
import {z} from 'zod';
import type {AdminPrincipal} from '../lib/adminAuth.js';
import {markAtomicallyAudited} from '../lib/adminAudit.js';
import {AcquisitionAdminService} from '../providers/acquisitionAdminService.js';
import {SourceProtectionService} from '../providers/sourceProtectionService.js';
import {PersistentSchedulerService} from '../providers/schedulerService.js';

const uuid=z.string().uuid(),year=z.number().int().min(1950).max(2200);
const principal=(request:FastifyRequest)=>(request as FastifyRequest&{adminPrincipal:AdminPrincipal}).adminPrincipal;
const context=(request:FastifyRequest)=>({principal:principal(request),requestId:request.id});
const fail=(reply:any,error:unknown)=>{const message=(error as Error).message,known:Record<string,number>={source_entity_not_found:404,active_correction_not_found:404,field_path_invalid:400,observation_key_invalid:400,protection_payload_too_large:413,observation_details_invalid:400};const code=Number((error as {statusCode?:number}).statusCode??known[message]??500);if(code<500)return reply.code(code).send({message});throw error;};

export async function providerAcquisitionAdminRoutes(app:FastifyInstance,options:{admin:AcquisitionAdminService;protection:SourceProtectionService;scheduler:PersistentSchedulerService}){const {admin,protection,scheduler}=options;
  app.get('/api/v1/admin/provider-championships/:id/acquisition',async(request,reply)=>{const parsed=uuid.safeParse((request.params as any).id);if(!parsed.success)return reply.code(400).send({message:'Identifiant invalide.'});return await admin.overview(parsed.data)??reply.code(404).send({message:'Lien fournisseur introuvable.'});});
  app.get('/api/v1/admin/provider-acquisition/anomalies',async request=>{const parsed=z.object({championship_id:uuid.optional(),provider_id:uuid.optional(),type:z.string().max(128).optional(),state:z.enum(['active','resolved']).optional()}).safeParse(request.query);if(!parsed.success)return [];return admin.anomalies({championshipId:parsed.data.championship_id,providerId:parsed.data.provider_id,type:parsed.data.type,state:parsed.data.state});});
  app.get('/api/v1/admin/provider-source-entities/:id',async(request,reply)=>{const parsed=uuid.safeParse((request.params as any).id);if(!parsed.success)return reply.code(400).send({message:'Identifiant invalide.'});return await admin.source(parsed.data)??reply.code(404).send({message:'Entité source introuvable.'});});
  app.put('/api/v1/admin/provider-source-entities/:id/corrections/:fieldPath',async(request,reply)=>{const params=z.object({id:uuid,fieldPath:z.string()}).safeParse(request.params),body=z.object({override_value:z.unknown(),reason:z.string().trim().min(1).max(2000)}).strict().safeParse(request.body);if(!params.success||!body.success)return reply.code(400).send({message:'Correction invalide.'});try{const result=await protection.upsertCorrection({sourceEntityId:params.data.id,fieldPath:params.data.fieldPath,overrideValue:body.data.override_value,reason:body.data.reason,origin:'administrator',actorId:principal(request).sub});return result;}catch(error){return fail(reply,error);}});
  app.post('/api/v1/admin/provider-source-corrections/:id/deactivate',async(request,reply)=>{const parsed=uuid.safeParse((request.params as any).id);if(!parsed.success)return reply.code(400).send({message:'Identifiant invalide.'});try{return await protection.deactivateCorrection(parsed.data);}catch(error){return fail(reply,error);}});
  app.put('/api/v1/admin/provider-source-entities/:id/observations/:key',async(request,reply)=>{const params=z.object({id:uuid,key:z.string()}).safeParse(request.params),body=z.object({kind:z.string().trim().min(1).max(128),details:z.record(z.string(),z.unknown()),reason:z.string().trim().min(1).max(2000)}).strict().safeParse(request.body);if(!params.success||!body.success)return reply.code(400).send({message:'Observation invalide.'});try{return await protection.upsertObservation({sourceEntityId:params.data.id,observationKey:params.data.key,observationKind:body.data.kind,details:body.data.details,reason:body.data.reason,origin:'administrator',actorId:principal(request).sub});}catch(error){return fail(reply,error);}});
  app.post('/api/v1/admin/provider-source-entities/:id/resync',async(request,reply)=>{const parsed=uuid.safeParse((request.params as any).id);if(!parsed.success)return reply.code(400).send({message:'Identifiant invalide.'});try{const result=await scheduler.resyncEvent(parsed.data,context(request));markAtomicallyAudited(request);return reply.code(202).send(result);}catch(error){return fail(reply,error);}});
  app.post('/api/v1/admin/provider-championships/:id/acquisition/resync-season',async(request,reply)=>{const params=uuid.safeParse((request.params as any).id),body=z.object({season:year,confirmed:z.literal(true)}).strict().safeParse(request.body);if(!params.success||!body.success)return reply.code(400).send({message:'Confirmation et saison requises.'});try{const result=await scheduler.resyncSeason(params.data,body.data.season,context(request));markAtomicallyAudited(request);return reply.code(202).send(result);}catch(error){return fail(reply,error);}});
  app.post('/api/v1/admin/provider-championships/:id/acquisition/resume-history',async(request,reply)=>{const parsed=uuid.safeParse((request.params as any).id);if(!parsed.success)return reply.code(400).send({message:'Identifiant invalide.'});try{const result=await scheduler.resumeHistory(parsed.data,context(request));markAtomicallyAudited(request);return reply.code(202).send(result);}catch(error){return fail(reply,error);}});
  app.post('/api/v1/admin/provider-championships/:id/acquisition/rebuild-history',async(request,reply)=>{const params=uuid.safeParse((request.params as any).id),body=z.object({from_season:year,confirmed:z.literal(true)}).strict().safeParse(request.body);if(!params.success||!body.success)return reply.code(400).send({message:'Confirmation et saison de départ requises.'});try{const result=await scheduler.rebuildHistory(params.data,body.data.from_season,context(request));markAtomicallyAudited(request);return reply.code(202).send(result);}catch(error){return fail(reply,error);}});
}
