import type { FastifyInstance,FastifyRequest } from 'fastify';
import { z } from 'zod';
import type { AdminPrincipal } from '../lib/adminAuth.js';
import { markAtomicallyAudited } from '../lib/adminAudit.js';
import { ProviderDiscoveryService } from '../providers/discoveryService.js';

const uuid=z.string().uuid();
const context=(request:FastifyRequest)=>({principal:(request as FastifyRequest&{adminPrincipal:AdminPrincipal}).adminPrincipal,requestId:request.id});
const params=(value:unknown)=>z.object({id:uuid}).safeParse(value);
const discoveryParams=(value:unknown)=>z.object({id:uuid,discoveryId:uuid}).safeParse(value);
const fail=(reply:{code(value:number):{send(value:unknown):unknown}},error:unknown)=>{const code=Number((error as {statusCode?:number}).statusCode??500);if(code<500)return reply.code(code).send({message:(error as Error).message});throw error;};

export async function providerDiscoveryRoutes(app:FastifyInstance,options:{service:ProviderDiscoveryService}){const service=options.service;
  app.get('/api/v1/admin/providers/:id/discovery-config',async(request,reply)=>{const parsed=params(request.params);if(!parsed.success)return reply.code(400).send({message:'Identifiant invalide.'});return await service.config(parsed.data.id)??reply.code(404).send({message:'Fournisseur introuvable.'});});
  app.put('/api/v1/admin/providers/:id/discovery-config',async(request,reply)=>{const p=params(request.params),body=z.object({enabled:z.boolean(),interval_days:z.number().int().min(7)}).strict().safeParse(request.body);if(!p.success||!body.success)return reply.code(400).send({message:'Configuration de découverte invalide.'});const result=await service.setConfig(p.data.id,{enabled:body.data.enabled,intervalDays:body.data.interval_days},context(request));if(!result)return reply.code(404).send({message:'Fournisseur introuvable.'});markAtomicallyAudited(request);return result;});
  app.post('/api/v1/admin/providers/:id/test-connection',async(request,reply)=>{const p=params(request.params);if(!p.success)return reply.code(400).send({message:'Identifiant invalide.'});try{return await service.testConnection(p.data.id);}catch(error){return fail(reply,error);}});
  app.post('/api/v1/admin/providers/:id/discoveries/run',async(request,reply)=>{const p=params(request.params);if(!p.success)return reply.code(400).send({message:'Identifiant invalide.'});try{return await service.discover(p.data.id,'manual',context(request));}catch(error){return fail(reply,error);}});
  app.get('/api/v1/admin/providers/:id/discoveries',async(request,reply)=>{const p=params(request.params);if(!p.success)return reply.code(400).send({message:'Identifiant invalide.'});return service.list(p.data.id);});
  app.get('/api/v1/admin/providers/:id/discovery-runs',async(request,reply)=>{const p=params(request.params);if(!p.success)return reply.code(400).send({message:'Identifiant invalide.'});return service.history(p.data.id);});
  app.post('/api/v1/admin/providers/:id/discoveries/:discoveryId/associate',async(request,reply)=>{const p=discoveryParams(request.params),body=z.object({championship_id:z.string().min(1)}).strict().safeParse(request.body);if(!p.success||!body.success)return reply.code(400).send({message:'Association invalide.'});try{const result=await service.associate(p.data.id,p.data.discoveryId,body.data.championship_id,context(request));if(!result)return reply.code(404).send({message:'Découverte introuvable.'});markAtomicallyAudited(request);return result;}catch(error){if((error as {code?:string}).code==='23505')return reply.code(409).send({message:'Cette source est déjà associée.'});return fail(reply,error);}});
  app.post('/api/v1/admin/providers/:id/discoveries/:discoveryId/create-championship',async(request,reply)=>{const p=discoveryParams(request.params),body=z.object({name:z.string().trim().min(2).max(120),season:z.number().int().min(1950).max(2200)}).strict().safeParse(request.body);if(!p.success||!body.success)return reply.code(400).send({message:'Championnat invalide.'});try{const result=await service.createAndAssociate(p.data.id,p.data.discoveryId,body.data,context(request));if(!result)return reply.code(404).send({message:'Découverte introuvable.'});markAtomicallyAudited(request);return reply.code(201).send(result);}catch(error){return fail(reply,error);}});
  app.post('/api/v1/admin/providers/:id/discoveries/:discoveryId/adopt',async(request,reply)=>{const p=discoveryParams(request.params);if(!p.success)return reply.code(400).send({message:'Identifiant invalide.'});try{const result=await service.adopt(p.data.id,p.data.discoveryId,context(request));if(!result)return reply.code(404).send({message:'Découverte introuvable.'});markAtomicallyAudited(request);return result;}catch(error){return fail(reply,error);}});
}
