import { adminAuthorization, notifyAuthenticationRequired } from '../../lib/adminAuth';

const API = import.meta.env.VITE_API_URL ?? 'http://localhost:3001';
export type Provider={id:string;name:string;adapter_key:string;state:string;enabled:boolean};
export type Discovery={id:string;name:string;provider_championship_id:string|null;state:string};
export type AcquisitionOverview={provider_championship:Record<string,any>;current:Record<string,any>;finalization:Record<string,any>;history:Record<string,any>;recent_runs:Record<string,any>[];allowed_actions:string[]};
export type Anomaly={id:string;provider_championship_id:string;provider_instance_id:string;championship_id:string;source_entity_id:string|null;anomaly_type:string;scope:string;state:'active'|'resolved';details:Record<string,unknown>;first_seen_at:string;last_seen_at:string;occurrence_count:number};
export type SourceDetail={entity:Record<string,any>;manual_correction_active:boolean;corrections:Record<string,any>[];local_observations:Record<string,any>[];source_changes:Record<string,any>[];anomalies:Anomaly[]};
export class AcquisitionApiError extends Error{constructor(message:string,readonly status:number){super(message)}}
export async function acquisitionRequest<T>(path:string,init:RequestInit={}):Promise<T>{const headers=new Headers(init.headers);for(const [name,value] of Object.entries(adminAuthorization()))headers.set(name,value);if(init.body)headers.set('content-type','application/json');const response=await fetch(API+path,{...init,credentials:'include',headers});if(response.status===401)notifyAuthenticationRequired();if(!response.ok){const body=await response.json().catch(()=>({})) as {message?:string};throw new AcquisitionApiError(body.message??(response.status===403?'Action réservée aux administrateurs.':response.status===409?'Action impossible pendant un traitement en cours.':'Erreur de supervision fournisseur.'),response.status)}return response.status===204?undefined as T:response.json()}
export async function listProviderChampionships(){const providers=await acquisitionRequest<Provider[]>('/api/v1/admin/providers');const groups=await Promise.all(providers.map(async provider=>({provider,discoveries:await acquisitionRequest<Discovery[]>(`/api/v1/admin/providers/${provider.id}/discoveries`)})));return groups.flatMap(({provider,discoveries})=>discoveries.filter(item=>item.provider_championship_id).map(item=>({id:item.provider_championship_id!,label:`${item.name} — ${provider.name}`,providerId:provider.id,championshipName:item.name,providerName:provider.name}))).sort((a,b)=>a.label.localeCompare(b.label,'fr'))}
export const loadOverview=(id:string)=>acquisitionRequest<AcquisitionOverview>(`/api/v1/admin/provider-championships/${id}/acquisition`);
export function loadAnomalies(filters:{championshipId?:string;providerId?:string;type?:string;state?:string}={}){const query=new URLSearchParams();if(filters.championshipId)query.set('championship_id',filters.championshipId);if(filters.providerId)query.set('provider_id',filters.providerId);if(filters.type)query.set('type',filters.type);if(filters.state)query.set('state',filters.state);return acquisitionRequest<Anomaly[]>(`/api/v1/admin/provider-acquisition/anomalies${query.size?`?${query}`:''}`)}
export const loadSource=(id:string)=>acquisitionRequest<SourceDetail>(`/api/v1/admin/provider-source-entities/${id}`);
export const saveCorrection=(id:string,path:string,value:unknown,reason:string)=>acquisitionRequest(`/api/v1/admin/provider-source-entities/${id}/corrections/${encodeURIComponent(path)}`,{method:'PUT',body:JSON.stringify({override_value:value,reason})});
export const deactivateCorrection=(id:string)=>acquisitionRequest(`/api/v1/admin/provider-source-corrections/${id}/deactivate`,{method:'POST'});
export const saveObservation=(id:string,key:string,kind:string,details:Record<string,unknown>,reason:string)=>acquisitionRequest(`/api/v1/admin/provider-source-entities/${id}/observations/${encodeURIComponent(key)}`,{method:'PUT',body:JSON.stringify({kind,details,reason})});
export const resyncEvent=(id:string)=>acquisitionRequest(`/api/v1/admin/provider-source-entities/${id}/resync`,{method:'POST'});
export const resyncSeason=(id:string,season:number)=>acquisitionRequest(`/api/v1/admin/provider-championships/${id}/acquisition/resync-season`,{method:'POST',body:JSON.stringify({season,confirmed:true})});
export const resumeHistory=(id:string)=>acquisitionRequest(`/api/v1/admin/provider-championships/${id}/acquisition/resume-history`,{method:'POST'});
export const rebuildHistory=(id:string,fromSeason:number)=>acquisitionRequest(`/api/v1/admin/provider-championships/${id}/acquisition/rebuild-history`,{method:'POST',body:JSON.stringify({from_season:fromSeason,confirmed:true})});
export const safeJson=(value:string):unknown=>{try{return JSON.parse(value)}catch{return value}};
