import { createHash, randomUUID } from 'node:crypto';
import type { PoolClient } from 'pg';
import { pool } from '../lib/db.js';
import type { AdminPrincipal } from '../lib/adminAuth.js';
import type { JsonObject, JsonValue } from './contracts.js';
import { ProviderConfigurationService } from './providerService.js';
import { redactProviderData } from './providerSecrets.js';

export type DiscoveryContext={principal:AdminPrincipal;requestId:string};
const status=(code:number,message:string)=>Object.assign(new Error(message),{statusCode:code});
const stable=(value:JsonValue):string=>Array.isArray(value)?`[${value.map(stable).join(',')}]`:value&&typeof value==='object'?`{${Object.keys(value).sort().map(k=>`${JSON.stringify(k)}:${stable(value[k]!)}`).join(',')}}`:JSON.stringify(value);
const hash=(value:JsonObject)=>createHash('sha256').update(stable(value)).digest('hex');
const counter=()=>{let count=0;return {increment(){count+=1;},get value(){return count;}};};

async function audit(client:PoolClient,context:DiscoveryContext,action:string,id:string,oldValue:unknown,newValue:unknown){
  await client.query(`insert into admin_audit_log(actor,action,resource_type,resource_id,request_id,old_value,new_value)
    values($1,$2,'provider_discovery',$3,$4,$5::jsonb,$6::jsonb)`,[context.principal.sub,action,id,context.requestId,JSON.stringify(redactProviderData(oldValue)),JSON.stringify(redactProviderData(newValue))]);
}
async function tx<T>(operation:(client:PoolClient)=>Promise<T>){const client=await pool.connect();try{await client.query('begin');const value=await operation(client);await client.query('commit');return value;}catch(error){await client.query('rollback');throw error;}finally{client.release();}}

export class ProviderDiscoveryService {
  constructor(readonly providers:ProviderConfigurationService){}
  async config(id:string){const row=(await pool.query(`select discovery_enabled,discovery_interval_days,last_discovery_at,
    case when last_discovery_at is null then now() else last_discovery_at + make_interval(days=>discovery_interval_days) end as next_discovery_at
    from provider_instances where id=$1`,[id])).rows[0];return row??null;}
  async setConfig(id:string,value:{enabled:boolean;intervalDays:number},context:DiscoveryContext){return tx(async client=>{
    const before=(await client.query('select discovery_enabled,discovery_interval_days,last_discovery_at from provider_instances where id=$1 for update',[id])).rows[0];if(!before)return null;
    const after=(await client.query(`update provider_instances set discovery_enabled=$2,discovery_interval_days=$3,updated_at=now() where id=$1 returning discovery_enabled,discovery_interval_days,last_discovery_at`,[id,value.enabled,value.intervalDays])).rows[0];
    await audit(client,context,'provider.discovery_configuration_changed',id,before,after);return after;});}
  async isDue(id:string,now=new Date()){const value=await this.config(id);return Boolean(value?.discovery_enabled)&&(!value.last_discovery_at||new Date(value.next_discovery_at)<=now);}
  async list(id:string){return (await pool.query('select * from provider_discovered_championships where provider_instance_id=$1 order by lower(name),external_championship_id',[id])).rows;}
  async history(id:string){return (await pool.query('select * from provider_discovery_runs where provider_instance_id=$1 order by started_at desc limit 100',[id])).rows;}
  async testConnection(id:string){const provider=await this.providers.get(id);if(!provider)throw status(404,'Fournisseur introuvable.');const adapter=this.providers.registry.get(provider.adapter_key);if(!adapter?.testConnection)throw status(409,'Test de connexion non supporté.');
    const apiKey=await this.providers.readSecretForAdapter(id,'api_key');const requests=counter();return {...await adapter.testConnection({providerInstanceId:id,providerConfig:provider.config,credentials:apiKey?{api_key:apiKey}:{},requestCounter:requests}),request_count:requests.value};}
  async discover(id:string,origin:'manual'|'periodic',context:DiscoveryContext){
    const provider=await this.providers.get(id);if(!provider)throw status(404,'Fournisseur introuvable.');const adapter=this.providers.registry.get(provider.adapter_key);if(!adapter?.discoverChampionships)throw status(409,'Découverte non supportée.');
    const policy=await this.providers.quotaPolicy(id);const quota=(await pool.query('select internally_consumed_monthly from provider_quota_state where provider_instance_id=$1',[id])).rows[0];
    if(policy?.monthly_limit!=null&&Number(quota?.internally_consumed_monthly??0)>=Math.floor(Number(policy.monthly_limit)*(1-Number(provider.current_year_reserve_percent)/100))){
      return (await pool.query(`insert into provider_discovery_runs(id,provider_instance_id,origin,status,finished_at,duration_ms,deferred_reason,request_id) values($1,$2,$3,'deferred_quota',now(),0,'Réserve annuelle protégée.',$4) returning *`,[randomUUID(),id,origin,context.requestId])).rows[0];}
    const runId=randomUUID();await pool.query(`insert into provider_discovery_runs(id,provider_instance_id,origin,status,request_id) values($1,$2,$3,'running',$4)`,[runId,id,origin,context.requestId]);
    const requests=counter();const seen=new Set<string>();let fresh=0,divergences=0;
    try{const apiKey=await this.providers.readSecretForAdapter(id,'api_key');for await(const item of adapter.discoverChampionships({providerInstanceId:id,providerConfig:provider.config,credentials:apiKey?{api_key:apiKey}:{},requestCounter:requests})){
      const proposed=adapter.validateSourceConfig(item.sourceConfig,{providerConfig:provider.config});const proposedHash=hash(proposed);seen.add(item.externalChampionshipId);
      const result=await pool.query(`insert into provider_discovered_championships(id,provider_instance_id,external_championship_id,name,metadata,proposed_source_config,proposed_source_config_version,proposed_source_config_hash)
        values($1,$2,$3,$4,$5::jsonb,$6::jsonb,$7,$8) on conflict(provider_instance_id,external_championship_id) do update set name=excluded.name,metadata=excluded.metadata,proposed_source_config=excluded.proposed_source_config,proposed_source_config_version=excluded.proposed_source_config_version,proposed_source_config_hash=excluded.proposed_source_config_hash,last_discovered_at=now(),missing_complete_cycles=0,state=case when provider_discovered_championships.provider_championship_id is null then 'needs_association' else 'associated' end,source_config_diverged=case when provider_discovered_championships.provider_championship_id is null then false else exists(select 1 from provider_championship_source_configs c where c.provider_championship_id=provider_discovered_championships.provider_championship_id and c.config is distinct from excluded.proposed_source_config) end,updated_at=now() returning (xmax=0) as inserted,source_config_diverged`,[randomUUID(),id,item.externalChampionshipId,item.name,JSON.stringify(item.metadata??{}),JSON.stringify(proposed),adapter.sourceConfigVersion,proposedHash]);
      if(result.rows[0].inserted)fresh++;if(result.rows[0].source_config_diverged)divergences++;}
      const missing=(await pool.query(`update provider_discovered_championships set missing_complete_cycles=missing_complete_cycles+1,state=case when missing_complete_cycles+1>=3 then 'not_found' else state end,updated_at=now() where provider_instance_id=$1 and not(external_championship_id=any($2::text[])) returning state`,[id,[...seen]])).rows.filter(row=>row.state==='not_found').length;
      await pool.query(`update provider_instances set last_discovery_at=now(),updated_at=now() where id=$1`,[id]);
      const run=(await pool.query(`update provider_discovery_runs set status='completed',finished_at=now(),duration_ms=greatest(0,(extract(epoch from(now()-started_at))*1000)::int),request_count=$2,found_count=$3,new_count=$4,not_found_count=$5,divergence_count=$6 where id=$1 returning *`,[runId,requests.value,seen.size,fresh,missing,divergences])).rows[0];
      await pool.query(`insert into provider_quota_state(provider_instance_id,internally_consumed_monthly) values($1,$2) on conflict(provider_instance_id) do update set internally_consumed_monthly=provider_quota_state.internally_consumed_monthly+excluded.internally_consumed_monthly,version=provider_quota_state.version+1,updated_at=now()`,[id,requests.value]);return run;
    }catch(error){const message=(error as Error).message.replace(/https?:\/\/\S+/g,'[URL expurgée]').slice(0,500);await pool.query(`update provider_discovery_runs set status='failed',finished_at=now(),duration_ms=greatest(0,(extract(epoch from(now()-started_at))*1000)::int),request_count=$2,error_code=$3,error_message=$4 where id=$1`,[runId,requests.value,(error as {code?:string}).code??'discovery_failed',message]);throw error;}
  }
  async associate(providerId:string,discoveryId:string,championshipId:string,context:DiscoveryContext){return tx(async client=>{const discovered=(await client.query('select * from provider_discovered_championships where id=$1 and provider_instance_id=$2 for update',[discoveryId,providerId])).rows[0];if(!discovered)return null;
    const adapter=this.providers.registry.get((await client.query('select adapter_key from provider_instances where id=$1',[discovered.provider_instance_id])).rows[0].adapter_key)!;
    const linkId=randomUUID();const link=(await client.query(`insert into provider_championships(id,provider_instance_id,championship_id,external_championship_id,discovery_state,sync_state,is_primary,discovered_at) values($1,$2,$3,$4,'configured','inactive',false,now()) returning *`,[linkId,discovered.provider_instance_id,championshipId,discovered.external_championship_id])).rows[0];
    await client.query(`insert into provider_championship_source_configs(provider_championship_id,schema_version,config,validated_at) values($1,$2,$3::jsonb,now())`,[linkId,adapter.sourceConfigVersion,JSON.stringify(discovered.proposed_source_config)]);
    await client.query(`update provider_discovered_championships set provider_championship_id=$2,state='associated',source_config_diverged=false,updated_at=now() where id=$1`,[discoveryId,linkId]);await audit(client,context,'provider.discovery_associated',discoveryId,null,link);return link;});}
  async createAndAssociate(providerId:string,discoveryId:string,input:{name:string;season:number},context:DiscoveryContext){return tx(async client=>{const discovered=(await client.query('select * from provider_discovered_championships where id=$1 and provider_instance_id=$2 for update',[discoveryId,providerId])).rows[0];if(!discovered)return null;
    const championshipId=randomUUID();const base=input.name.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'championship';const slug=`${base}-${championshipId.slice(0,8)}`;
    const championship=(await client.query(`insert into championships(id,slug,name,season,active,sync_enabled) values($1,$2,$3,$4,true,false) returning *`,[championshipId,slug,input.name,input.season])).rows[0];
    const adapterKey=(await client.query('select adapter_key from provider_instances where id=$1',[discovered.provider_instance_id])).rows[0].adapter_key;const adapter=this.providers.registry.get(adapterKey)!;const linkId=randomUUID();
    const link=(await client.query(`insert into provider_championships(id,provider_instance_id,championship_id,external_championship_id,discovery_state,sync_state,is_primary,discovered_at) values($1,$2,$3,$4,'configured','inactive',false,now()) returning *`,[linkId,discovered.provider_instance_id,championshipId,discovered.external_championship_id])).rows[0];
    await client.query(`insert into provider_championship_source_configs(provider_championship_id,schema_version,config,validated_at) values($1,$2,$3::jsonb,now())`,[linkId,adapter.sourceConfigVersion,JSON.stringify(discovered.proposed_source_config)]);await client.query(`update provider_discovered_championships set provider_championship_id=$2,state='associated',source_config_diverged=false,updated_at=now() where id=$1`,[discoveryId,linkId]);await audit(client,context,'provider.discovery_championship_created',discoveryId,null,{championship,link});return {championship,link};});}
  async adopt(providerId:string,discoveryId:string,context:DiscoveryContext){return tx(async client=>{const discovered=(await client.query('select * from provider_discovered_championships where id=$1 and provider_instance_id=$2 for update',[discoveryId,providerId])).rows[0];if(!discovered)return null;if(!discovered.provider_championship_id)throw status(409,'Découverte non associée.');
    const before=(await client.query('select * from provider_championship_source_configs where provider_championship_id=$1 for update',[discovered.provider_championship_id])).rows[0];const after=(await client.query(`update provider_championship_source_configs set schema_version=$2,config=$3::jsonb,validated_at=now(),updated_at=now() where provider_championship_id=$1 returning *`,[discovered.provider_championship_id,discovered.proposed_source_config_version,JSON.stringify(discovered.proposed_source_config)])).rows[0];await client.query('update provider_discovered_championships set source_config_diverged=false,updated_at=now() where id=$1',[discoveryId]);await audit(client,context,'provider.discovery_config_adopted',discoveryId,before,after);return after;});}
}
