import assert from 'node:assert/strict';
import { Buffer } from 'node:buffer';
import { randomUUID } from 'node:crypto';
import { pool } from '../apps/api/dist/lib/db.js';
import { ProviderAdapterRegistry } from '../apps/api/dist/providers/registry.js';
import { ProviderSecretCipher } from '../apps/api/dist/providers/providerSecrets.js';
import { ProviderConfigurationService } from '../apps/api/dist/providers/providerService.js';
import { ProviderDiscoveryService } from '../apps/api/dist/providers/discoveryService.js';

const registry=new ProviderAdapterRegistry(),context={principal:{sub:'lot53-validation',role:'admin'},requestId:'lot53-validation'};
let next={items:[{externalChampionshipId:'series-a',name:'Series A',sourceConfig:{strategy:'fake-v1',external_id:'series-a'}}],complete:false,provenance:'provider-discovered'};let fail=false;let calls=0;
registry.register({key:'fake-discovery',capabilities:{supportsChampionshipDiscovery:true,supportsSeasonDiscovery:false,supportsQuotaHeaders:false,supportsConnectionTest:true},providerConfigVersion:1,sourceConfigVersion:1,cursorVersion:1,providerForm:()=>[],championshipForm:()=>[],validateProviderConfig(value){if(value?.mode!=='fixture')throw new Error('invalid');return value;},validateSourceConfig(value){if(value?.strategy!=='fake-v1'||typeof value?.external_id!=='string')throw new Error('invalid');return value;},async testConnection(ctx){ctx.requestCounter.increment();calls++;if(fail)throw new Error('HTTP 500');return {ok:true,message:'ok',checkedAt:new Date().toISOString()};},async discoverChampionships(ctx){ctx.requestCounter.increment();calls++;if(fail)throw new Error('HTTP 500');return next;},initialCursor:()=>({page:1}),validateCursor:value=>value,serializeCursor:value=>value,restoreCursor:value=>value,fetchWorkUnit:async()=>{throw new Error('anti-sync');},normalize:()=>({accepted:[],rejected:[]}),confirmEmptySeason:async()=>({confirmedEmpty:false,reason:'unused'})});

const providers=new ProviderConfigurationService(registry,new ProviderSecretCipher(new Map([[1,Buffer.alloc(32,7)]]),1));const discovery=new ProviderDiscoveryService(providers);let providerId;let championshipId;
try{
  const eventsBefore=Number((await pool.query('select count(*) from events')).rows[0].count);
  const provider=await providers.create({name:`Lot 5.3 fixture ${randomUUID()}`,adapterKey:'fake-discovery',config:{mode:'fixture'},enabled:false,maxConcurrency:1,currentYearReservePercent:30,missingCyclesThreshold:3,logRetentionDays:30},context);providerId=provider.id;await providers.replaceSecret(providerId,'api_key','fixture-secret',context);
  assert.deepEqual(await discovery.testConnection(providerId),{status:'deferred_quota',reason:'quota_unknown',request_count:0});assert.equal(calls,0);
  const deferred=await discovery.discover(providerId,'manual',context);assert.equal(deferred.status,'deferred_quota');assert.equal(deferred.request_count,0);assert.equal(calls,0);
  await providers.setQuotaPolicy(providerId,{shortWindowSeconds:null,shortLimit:null,monthlyLimit:100,limitsSource:'configured',resetTimezone:null,resetAt:null},context);
  const connection=await discovery.testConnection(providerId);assert.equal(connection.request_count,1);assert.equal(Number((await pool.query('select internally_consumed_monthly from provider_quota_state where provider_instance_id=$1',[providerId])).rows[0].internally_consumed_monthly),1);
  let run=await discovery.discover(providerId,'manual',context);assert.equal(run.status,'partial');assert.equal(run.is_complete,false);
  const discovered=(await pool.query('select * from provider_discovered_championships where provider_instance_id=$1',[providerId])).rows[0];assert.equal(discovered.missing_complete_cycles,0);
  next={items:[],complete:false,provenance:'provider-discovered'};await discovery.discover(providerId,'manual',context);assert.equal(Number((await pool.query('select missing_complete_cycles from provider_discovered_championships where id=$1',[discovered.id])).rows[0].missing_complete_cycles),0);
  next={items:[],complete:true,provenance:'provider-discovered'};for(let i=0;i<3;i++)await discovery.discover(providerId,'manual',context);const missing=(await pool.query('select missing_complete_cycles,state from provider_discovered_championships where id=$1',[discovered.id])).rows[0];assert.equal(missing.missing_complete_cycles,3);assert.equal(missing.state,'not_found');
  fail=true;const beforeFailure=Number((await pool.query('select internally_consumed_monthly from provider_quota_state where provider_instance_id=$1',[providerId])).rows[0].internally_consumed_monthly);await assert.rejects(()=>discovery.discover(providerId,'manual',context));assert.equal(Number((await pool.query('select internally_consumed_monthly from provider_quota_state where provider_instance_id=$1',[providerId])).rows[0].internally_consumed_monthly),beforeFailure+1);await assert.rejects(()=>discovery.testConnection(providerId));assert.equal(Number((await pool.query('select internally_consumed_monthly from provider_quota_state where provider_instance_id=$1',[providerId])).rows[0].internally_consumed_monthly),beforeFailure+2);fail=false;
  championshipId=randomUUID();await pool.query(`insert into championships(id,slug,name,season,active,sync_enabled) values($1,$2,'Lot 5.3 championship',2026,true,false)`,[championshipId,`lot53-${championshipId.slice(0,8)}`]);await discovery.associate(providerId,discovered.id,championshipId,context);const link=(await pool.query('select provider_championship_id from provider_discovered_championships where id=$1',[discovered.id])).rows[0].provider_championship_id;const approvedBefore=(await pool.query('select config from provider_championship_source_configs where provider_championship_id=$1',[link])).rows[0].config;
  await pool.query(`update provider_discovered_championships set proposed_source_config='{"strategy":"tampered"}'::jsonb where id=$1`,[discovered.id]);await assert.rejects(()=>discovery.adopt(providerId,discovered.id,context),error=>error.statusCode===409);assert.deepEqual((await pool.query('select config from provider_championship_source_configs where provider_championship_id=$1',[link])).rows[0].config,approvedBefore);
  await pool.query(`update provider_discovered_championships set proposed_source_config='{"strategy":"fake-v1","external_id":"series-a-v2"}'::jsonb where id=$1`,[discovered.id]);const adopted=await discovery.adopt(providerId,discovered.id,context);assert.equal(adopted.config.external_id,'series-a-v2');
  assert.equal(Number((await pool.query('select count(*) from events')).rows[0].count),eventsBefore);assert.equal((await pool.query("select to_regclass('public.sync_streams')::text as table_name")).rows[0].table_name,null);
  await pool.query('update provider_quota_state set internally_consumed_monthly=70 where provider_instance_id=$1',[providerId]);const boundary=await discovery.discover(providerId,'manual',context);assert.equal(boundary.status,'deferred_quota');assert.equal(boundary.request_count,0);
  console.log('Quota inconnu/limite, complétude, erreurs, adoption et anti-sync Lot 5.3 : OK');
}finally{if(providerId)await pool.query('delete from provider_instances where id=$1',[providerId]);if(championshipId)await pool.query('delete from championships where id=$1',[championshipId]);await pool.end();}
