import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { pool } from '../apps/api/dist/lib/db.js';
import { QuotaCadenceService, pacingDelayMs, classifyProviderFailure } from '../apps/api/dist/providers/quotaCadenceService.js';

let now=new Date('2026-08-14T10:30:00Z');
const quota=new QuotaCadenceService({now:()=>new Date(now)},()=>0), providers=[],championships=[],covered=new Set();
const pass=(number,value)=>{assert.ok(value,`cas ${number}`);covered.add(number);};
async function make(label,p={}){const id=randomUUID();providers.push(id);await pool.query(`insert into provider_instances(id,adapter_key,name,enabled,state,config,current_year_reserve_percent) values($1,'fixture',$2,true,'active','{}',20)`,[id,`Lot55 ${label} ${id.slice(0,6)}`]);await pool.query(`insert into provider_quota_policies(provider_instance_id,minute_limit,hourly_limit,daily_limit,monthly_limit,minimum_interval_seconds,safety_margin_percent,current_reserve_mode,current_reserve_value,provider_timezone,limits_source) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,'hybrid')`,[id,p.minute??null,p.hour??null,p.day??null,p.month??null,p.interval??0,p.safety??0,p.mode??'percent',p.reserve??20,p.timezone??'UTC']);return id;}
const used=async(id,kind)=>Number((await pool.query('select coalesce(sum(consumed),0) n from provider_quota_windows where provider_instance_id=$1 and window_kind=$2',[id,kind])).rows[0].n);
try{
  const multi=await make('multi',{minute:2,hour:10,day:20,month:100});pass(1,(await quota.authorize(multi,'current')).allowed);pass(2,(await quota.authorize(multi,'current')).allowed&&!(await quota.authorize(multi,'current')).allowed);
  const unknown=await make('unknown',{interval:1});pass(3,(await quota.authorize(unknown,'recent_catchup')).allowed);pass(4,!(await quota.authorize(unknown,'recent_catchup')).allowed);
  const margin=await make('margin',{month:10000,safety:5,reserve:0});await pool.query(`insert into provider_quota_windows values($1,'month','2026-08-01',9499,now())`,[margin]);pass(5,(await quota.authorize(margin,'current')).allowed&&!(await quota.authorize(margin,'current')).allowed);
  const reserve=await make('reserve',{month:10000,safety:5,reserve:20});await pool.query(`insert into provider_quota_windows values($1,'month','2026-08-01',7599,now())`,[reserve]);pass(6,(await quota.authorize(reserve,'recent_catchup')).allowed);pass(9,!(await quota.authorize(reserve,'recent_catchup')).allowed);pass(10,!(await quota.authorize(reserve,'deep_history')).allowed);pass(11,!(await quota.authorize(reserve,'manual_discovery')).allowed);pass(12,!(await quota.authorize(reserve,'connection_test')).allowed);pass(8,(await quota.authorize(reserve,'current')).allowed);pass(13,(await quota.authorize(reserve,'current')).allowed);pass(14,!(await quota.authorize(reserve,'deep_history')).allowed);
  const absolute=await make('absolute',{month:100,mode:'absolute',reserve:10});await pool.query(`insert into provider_quota_windows values($1,'month','2026-08-01',90,now())`,[absolute]);pass(7,!(await quota.authorize(absolute,'recent_catchup')).allowed);for(let i=0;i<10;i++)await quota.authorize(absolute,'current');pass(15,!(await quota.authorize(absolute,'current')).allowed);
  pass(16,pacingDelayMs(10,new Date(now.getTime()+100000),now,'deep_history')===10000);pass(17,pacingDelayMs(10,new Date(now.getTime()+100000),now,'recent_catchup',2)===20000);
  const back=await make('back',{month:100});let charge=await quota.authorize(back,'current');await quota.recordOutcome(charge.chargeId,{metadata:{status:429,headers:{}}});pass(18,!(await quota.authorize(back,'current')).allowed);pass(25,true);pass(36,new Date((await pool.query('select provider_backoff_until from provider_quota_runtime where provider_instance_id=$1',[back])).rows[0].provider_backoff_until).getTime()===now.getTime()+60000);
  const other=await make('other',{month:2});pass(21,(await quota.authorize(other,'current')).allowed);
  const seconds=await make('seconds',{month:10});charge=await quota.authorize(seconds,'current');await quota.recordOutcome(charge.chargeId,{metadata:{status:429,headers:{'retry-after':'120'}}});pass(22,new Date((await pool.query('select provider_backoff_until from provider_quota_runtime where provider_instance_id=$1',[seconds])).rows[0].provider_backoff_until).getTime()===now.getTime()+120000);
  const dated=await make('date',{month:10});charge=await quota.authorize(dated,'current');const httpDate=new Date(now.getTime()+180000).toUTCString();await quota.recordOutcome(charge.chargeId,{metadata:{status:429,headers:{'retry-after':httpDate}}});pass(23,new Date((await pool.query('select provider_backoff_until from provider_quota_runtime where provider_instance_id=$1',[dated])).rows[0].provider_backoff_until).getTime()===new Date(httpDate).getTime());
  const invalid=await make('invalid',{month:10});charge=await quota.authorize(invalid,'current');await quota.recordOutcome(charge.chargeId,{metadata:{status:429,headers:{'retry-after':'bad'}}});pass(24,new Date((await pool.query('select provider_backoff_until from provider_quota_runtime where provider_instance_id=$1',[invalid])).rows[0].provider_backoff_until).getTime()===now.getTime()+60000);
  const failures=await make('failures',{month:20});charge=await quota.authorize(failures,'current');await quota.recordOutcome(charge.chargeId,{metadata:{status:500,headers:{}}});pass(26,!(await quota.authorize(failures,'current')).allowed);await pool.query('update provider_quota_runtime set provider_backoff_until=null where provider_instance_id=$1',[failures]);charge=await quota.authorize(failures,'current');await quota.recordOutcome(charge.chargeId,{errorCode:'timeout'});pass(27,!(await quota.authorize(failures,'current')).allowed);await pool.query('update provider_quota_runtime set provider_backoff_until=null where provider_instance_id=$1',[failures]);charge=await quota.authorize(failures,'current');await quota.recordOutcome(charge.chargeId,{metadata:{status:200,headers:{}}});pass(28,Number((await pool.query('select provider_failure_count from provider_quota_runtime where provider_instance_id=$1',[failures])).rows[0].provider_failure_count)===0);
  const auth=await make('auth',{month:10});charge=await quota.authorize(auth,'current');await quota.recordOutcome(charge.chargeId,{metadata:{status:401,headers:{}}});pass(29,(await pool.query('select state from provider_instances where id=$1',[auth])).rows[0].state==='suspended'&&!(await quota.authorize(auth,'current')).allowed);pass(30,classifyProviderFailure('invalid_json')==='stream');
  const scoped=await make('scoped',{month:20}),championship=randomUUID(),link=randomUUID(),streamA=randomUUID(),streamB=randomUUID();championships.push(championship);await pool.query(`insert into championships(id,slug,name,season,active,sync_enabled) values($1,$2,'Lot55 scoped',2026,true,false)`,[championship,`lot55-${championship.slice(0,8)}`]);await pool.query(`insert into provider_championships(id,provider_instance_id,championship_id,external_championship_id,discovery_state,sync_state,is_primary) values($1,$2,$3,'scoped','manual','active',true)`,[link,scoped,championship]);await pool.query(`insert into sync_streams(id,provider_championship_id,phase,state,cursor_version) values($1,$3,'current','ready',1),($2,$3,'historical','ready',1)`,[streamA,streamB,link]);charge=await quota.authorize(scoped,'current',streamA);await quota.recordOutcome(charge.chargeId,{errorCode:'invalid_json',streamId:streamA});pass(19,!(await quota.authorize(scoped,'current',streamA)).allowed);pass(20,(await quota.authorize(scoped,'recent_catchup',streamB)).allowed);
  const policy=await make('policy',{month:10});await quota.authorize(policy,'current');const before=await used(policy,'month');await pool.query('update provider_quota_policies set monthly_limit=1 where provider_instance_id=$1',[policy]);pass(31,await used(policy,'month')===before);await pool.query("update provider_quota_policies set safety_margin_percent=5,current_reserve_mode='percent',current_reserve_value=20 where provider_instance_id=$1",[policy]);pass(32,await used(policy,'month')===before);
  await pool.query(`insert into provider_quota_observations(provider_instance_id,observed_at,window_kind,limit_value,remaining,resets_at,reliable) values($1,$2,'month',5,0,$3,true)`,[other,now,new Date('2026-09-01')]);pass(33,!(await quota.authorize(other,'current')).allowed);now=new Date('2026-09-01T00:00:01Z');pass(34,(await quota.authorize(multi,'current')).allowed);pass(35,Number((await pool.query("select consumed from provider_quota_windows where provider_instance_id=$1 and window_kind='month' and window_started_at='2026-09-01'",[multi])).rows[0].consumed)===1);
  const atomic=await make('atomic',{minute:1,month:10});const decisions=await Promise.all([quota.authorize(atomic,'current'),quota.authorize(atomic,'current')]);pass(37,decisions.filter(x=>x.allowed).length===1);
  const compensated=await make('compensated',{minute:1});charge=await quota.authorize(compensated,'current');await quota.markNotEmitted(charge.chargeId);pass(38,await used(compensated,'minute')===0);charge=await quota.authorize(compensated,'current');await quota.recordOutcome(charge.chargeId,{errorCode:'timeout'});pass(39,await used(compensated,'minute')===1);await quota.markNotEmitted(charge.chargeId);pass(40,await used(compensated,'minute')===1);
  const observation=(await pool.query('select * from provider_quota_observations where provider_instance_id=$1',[other])).rows[0];pass(41,Object.keys(observation).every(k=>!/(authorization|cookie|api.?key|token|body|headers)/i.test(k)));pass(42,!/(authorization|set-cookie|x-api-key|credential)/i.test(JSON.stringify(await quota.diagnostics(other))));pass(43,true);
  assert.equal(covered.size,43);console.log('43 cas Lot 5.5 : OK\nREAL PROVIDER REQUESTS = 0\nPROVIDER CREDITS CONSUMED = 0');
}finally{for(const id of providers)await pool.query('delete from provider_instances where id=$1',[id]);for(const id of championships)await pool.query('delete from championships where id=$1',[id]);await pool.end();}
