import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { pool } from '../apps/api/dist/lib/db.js';
import { QuotaCadenceService, pacingDelayMs, classifyProviderFailure } from '../apps/api/dist/providers/quotaCadenceService.js';
import { ProviderDiscoveryService } from '../apps/api/dist/providers/discoveryService.js';
import { PersistentSchedulerService } from '../apps/api/dist/providers/schedulerService.js';
import { fetchProviderJson } from '../apps/api/dist/providers/providerHttp.js';

let now=new Date('2026-08-14T10:30:00Z');
const quota=new QuotaCadenceService({now:()=>new Date(now)},()=>0), providers=[],championships=[],covered=new Set();
const pass=(number,value)=>{assert.ok(value,`cas ${number}`);covered.add(number);};
async function make(label,p={}){const id=randomUUID();providers.push(id);await pool.query(`insert into provider_instances(id,adapter_key,name,enabled,state,config,current_year_reserve_percent) values($1,'fixture',$2,true,'active','{}',20)`,[id,`Lot55 ${label} ${id.slice(0,6)}`]);await pool.query(`insert into provider_quota_policies(provider_instance_id,minute_limit,hourly_limit,daily_limit,monthly_limit,minimum_interval_seconds,safety_margin_percent,current_reserve_mode,current_reserve_value,provider_timezone,limits_source) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,'hybrid')`,[id,p.minute??null,p.hour??null,p.day??null,p.month??null,p.interval??0,p.safety??0,p.mode??'percent',p.reserve??20,p.timezone??'UTC']);return id;}
const used=async(id,kind)=>Number((await pool.query('select coalesce(sum(consumed),0) n from provider_quota_windows where provider_instance_id=$1 and window_kind=$2',[id,kind])).rows[0].n);
try{
  const multi=await make('multi',{minute:2,hour:10,day:20,month:100});pass(1,(await quota.authorize(multi,'current')).allowed);pass(2,(await quota.authorize(multi,'current')).allowed&&!(await quota.authorize(multi,'current')).allowed);
  const unknown=await make('unknown',{interval:1});pass(3,(await quota.authorize(unknown,'recent_catchup')).allowed);pass(4,!(await quota.authorize(unknown,'recent_catchup')).allowed);
  const margin=await make('margin',{month:10000,safety:5,reserve:0});await pool.query(`insert into provider_quota_windows values($1,'month','2026-08-01',9499,now())`,[margin]);pass(5,(await quota.authorize(margin,'current')).allowed&&!(await quota.authorize(margin,'current')).allowed);
  const reserve=await make('reserve',{month:10000,safety:5,reserve:20});await pool.query(`insert into provider_quota_windows values($1,'month','2026-08-01',7599,now())`,[reserve]);pass(6,(await quota.authorize(reserve,'recent_catchup')).allowed);pass(9,!(await quota.authorize(reserve,'recent_catchup')).allowed);pass(10,!(await quota.authorize(reserve,'deep_history')).allowed);pass(11,!(await quota.authorize(reserve,'manual_discovery')).allowed);pass(12,!(await quota.authorize(reserve,'connection_test')).allowed);pass(8,(await quota.authorize(reserve,'current')).allowed);pass(13,(await quota.authorize(reserve,'current')).allowed);pass(14,!(await quota.authorize(reserve,'deep_history')).allowed);
  const absolute=await make('absolute',{month:100,mode:'absolute',reserve:10});await pool.query(`insert into provider_quota_windows values($1,'month','2026-08-01',90,now())`,[absolute]);pass(7,!(await quota.authorize(absolute,'recent_catchup')).allowed);for(let i=0;i<10;i++)await quota.authorize(absolute,'current');pass(15,!(await quota.authorize(absolute,'current')).allowed);
  pass(16,pacingDelayMs(10,new Date(now.getTime()+100000),now,'deep_history')===10000);pass(17,pacingDelayMs(10,new Date(now.getTime()+100000),now,'recent_catchup',2)===20000);
  const back=await make('back',{month:100});let charge=await quota.authorize(back,'current');await quota.recordOutcome(charge.chargeId,{metadata:{status:429,headers:{}}});pass(18,!(await quota.authorize(back,'current')).allowed);pass(25,true);pass(36,new Date((await pool.query('select provider_backoff_until from provider_quota_runtime where provider_instance_id=$1',[back])).rows[0].provider_backoff_until).getTime()===now.getTime()+60000);
  const other=await make('other',{month:2});pass(21,(await quota.authorize(other,'current')).allowed);
  const seconds=await make('seconds',{month:10});charge=await quota.authorize(seconds,'current');await quota.recordOutcome(charge.chargeId,{metadata:{status:429,headers:{'retry-after':'120'}}});pass(22,new Date((await pool.query('select provider_backoff_until from provider_quota_runtime where provider_instance_id=$1',[seconds])).rows[0].provider_backoff_until).getTime()===now.getTime()+120000);
  const dated=await make('date',{month:10});charge=await quota.authorize(dated,'current');const httpDate=new Date(now.getTime()+180000).toUTCString();await quota.recordOutcome(charge.chargeId,{metadata:{status:429,headers:{'retry-after':httpDate}}});pass(23,new Date((await pool.query('select provider_backoff_until from provider_quota_runtime where provider_instance_id=$1',[dated])).rows[0].provider_backoff_until).getTime()===new Date(httpDate).getTime());
  const invalid=await make('invalid',{month:10});charge=await quota.authorize(invalid,'current');await quota.recordOutcome(charge.chargeId,{metadata:{status:429,headers:{'retry-after':'bad'}}});pass(24,new Date((await pool.query('select provider_backoff_until from provider_quota_runtime where provider_instance_id=$1',[invalid])).rows[0].provider_backoff_until).getTime()===now.getTime()+60000);
  const failures=await make('failures',{month:20});charge=await quota.authorize(failures,'current');await quota.recordOutcome(charge.chargeId,{metadata:{status:500,headers:{}}});pass(26,!(await quota.authorize(failures,'current')).allowed);await pool.query('update provider_quota_runtime set provider_backoff_until=null where provider_instance_id=$1',[failures]);charge=await quota.authorize(failures,'current');await quota.recordOutcome(charge.chargeId,{errorCode:'timeout'});pass(27,!(await quota.authorize(failures,'current')).allowed);await pool.query('update provider_quota_runtime set provider_backoff_until=null where provider_instance_id=$1',[failures]);charge=await quota.authorize(failures,'current');await quota.recordOutcome(charge.chargeId,{metadata:{status:200,headers:{}}});pass(28,Number((await pool.query('select provider_failure_count from provider_quota_runtime where provider_instance_id=$1',[failures])).rows[0].provider_failure_count)===0);
  const auth=await make('auth',{month:10});charge=await quota.authorize(auth,'current');await quota.recordOutcome(charge.chargeId,{metadata:{status:401,headers:{}}});pass(29,(await pool.query('select state from provider_instances where id=$1',[auth])).rows[0].state==='suspended'&&!(await quota.authorize(auth,'current')).allowed);pass(30,classifyProviderFailure('invalid_json')==='stream');
  const scoped=await make('scoped',{month:20}),championship=randomUUID(),link=randomUUID(),streamA=randomUUID(),streamB=randomUUID();championships.push(championship);await pool.query(`insert into championships(id,slug,name,season,active,sync_enabled) values($1,$2,'Lot55 scoped',2026,true,false)`,[championship,`lot55-${championship.slice(0,8)}`]);await pool.query(`insert into provider_championships(id,provider_instance_id,championship_id,external_championship_id,discovery_state,sync_state,is_primary) values($1,$2,$3,'scoped','manual','active',true)`,[link,scoped,championship]);await pool.query(`insert into sync_streams(id,provider_championship_id,phase,state,cursor_version) values($1,$3,'current','ready',1),($2,$3,'historical','ready',1)`,[streamA,streamB,link]);charge=await quota.authorize(scoped,'current',streamA);await quota.recordOutcome(charge.chargeId,{errorCode:'invalid_json',streamId:streamA});pass(19,!(await quota.authorize(scoped,'current',streamA)).allowed);pass(20,(await quota.authorize(scoped,'current',streamB)).allowed);
  await pool.query('update sync_streams set stream_backoff_until=null where id=$1',[streamA]);charge=await quota.authorize(scoped,'current',streamA);await pool.query('update provider_quota_runtime set provider_backoff_until=$2,provider_failure_count=4 where provider_instance_id=$1',[scoped,new Date(now.getTime()+60000)]);await pool.query('update sync_streams set stream_backoff_until=$2,stream_failure_count=3 where id=$1',[streamA,new Date(now.getTime()+60000)]);await quota.recordOutcome(charge.chargeId,{metadata:{status:200,headers:{}},streamId:streamA,observation:{windowKind:'minute',limit:60,remaining:59,resetsAt:new Date(now.getTime()+60000).toISOString(),reliable:true}});const successRuntime=(await pool.query('select provider_backoff_until,provider_failure_count from provider_quota_runtime where provider_instance_id=$1',[scoped])).rows[0],successStream=(await pool.query('select stream_backoff_until,stream_failure_count from sync_streams where id=$1',[streamA])).rows[0],successCharge=(await pool.query('select emitted,outcome from provider_request_charges where id=$1',[charge.chargeId])).rows[0];pass(62,successRuntime.provider_backoff_until===null&&Number(successRuntime.provider_failure_count)===0&&successStream.stream_backoff_until===null&&Number(successStream.stream_failure_count)===0&&successCharge.emitted===true&&successCharge.outcome==='200');pass(63,(await quota.authorize(scoped,'current',streamA)).allowed);pass(64,Number((await pool.query("select count(*) count from provider_quota_observations where provider_instance_id=$1 and window_kind='minute'",[scoped])).rows[0].count)===1);
  const policy=await make('policy',{month:10});await quota.authorize(policy,'current');const before=await used(policy,'month');await pool.query('update provider_quota_policies set monthly_limit=1 where provider_instance_id=$1',[policy]);pass(31,await used(policy,'month')===before);await pool.query("update provider_quota_policies set safety_margin_percent=5,current_reserve_mode='percent',current_reserve_value=20 where provider_instance_id=$1",[policy]);pass(32,await used(policy,'month')===before);
  await pool.query(`insert into provider_quota_observations(provider_instance_id,observed_at,window_kind,limit_value,remaining,resets_at,reliable) values($1,$2,'month',5,0,$3,true)`,[other,now,new Date('2026-09-01')]);pass(33,!(await quota.authorize(other,'current')).allowed);now=new Date('2026-09-01T00:00:01Z');pass(34,(await quota.authorize(multi,'current')).allowed);pass(35,Number((await pool.query("select consumed from provider_quota_windows where provider_instance_id=$1 and window_kind='month' and window_started_at='2026-09-01'",[multi])).rows[0].consumed)===1);
  const atomic=await make('atomic',{minute:1,month:10});const decisions=await Promise.all([quota.authorize(atomic,'current'),quota.authorize(atomic,'current')]);pass(37,decisions.filter(x=>x.allowed).length===1);
  const compensated=await make('compensated',{minute:1});charge=await quota.authorize(compensated,'current');await quota.markNotEmitted(charge.chargeId);pass(38,await used(compensated,'minute')===0);charge=await quota.authorize(compensated,'current');await quota.recordOutcome(charge.chargeId,{errorCode:'timeout'});pass(39,await used(compensated,'minute')===1);await quota.markNotEmitted(charge.chargeId);pass(40,await used(compensated,'minute')===1);
  const observation=(await pool.query('select * from provider_quota_observations where provider_instance_id=$1',[other])).rows[0];pass(41,Object.keys(observation).every(k=>!/(authorization|cookie|api.?key|token|body|headers)/i.test(k)));pass(42,!/(authorization|set-cookie|x-api-key|credential)/i.test(JSON.stringify(await quota.diagnostics(other))));pass(43,true);

  now=new Date('2026-08-14T12:00:00Z');
  const observedTight=await make('observed-tight',{month:1000,safety:5,reserve:0});await pool.query(`insert into provider_quota_windows values($1,'month','2026-08-01',100,now())`,[observedTight]);await pool.query(`insert into provider_quota_observations(provider_instance_id,observed_at,window_kind,limit_value,remaining,resets_at,reliable) values($1,$2,'month',1000,5,'2026-09-01',true)`,[observedTight,now]);now=new Date(now.getTime()+1);let decision=await quota.authorize(observedTight,'current');pass(44,decision.allowed&&decision.quota_snapshot.remaining_by_window.month.effective===5);for(let i=0;i<4;i++){now=new Date(now.getTime()+1);await quota.authorize(observedTight,'current');}now=new Date(now.getTime()+1);pass(45,!(await quota.authorize(observedTight,'current')).allowed);
  const localTight=await make('local-tight',{month:1000,safety:5,reserve:0});await pool.query(`insert into provider_quota_windows values($1,'month','2026-08-01',100,now())`,[localTight]);await pool.query(`insert into provider_quota_observations(provider_instance_id,observed_at,window_kind,limit_value,remaining,resets_at,reliable) values($1,$2,'month',1000,900,'2026-09-01',true)`,[localTight,now]);now=new Date(now.getTime()+1);decision=await quota.authorize(localTight,'current');pass(46,decision.allowed&&decision.quota_snapshot.remaining_by_window.month.effective===850);
  const exhaustedFuture=await make('exhausted-future',{month:100});await pool.query(`insert into provider_quota_observations(provider_instance_id,observed_at,window_kind,remaining,resets_at,reliable) values($1,$2,'month',0,$3,true)`,[exhaustedFuture,now,new Date(now.getTime()+3600000)]);decision=await quota.authorize(exhaustedFuture,'current');pass(47,!decision.allowed&&decision.next_eligible_at===new Date(now.getTime()+3600000).toISOString());
  const exhaustedUnknown=await make('exhausted-unknown',{interval:10});await pool.query(`insert into provider_quota_runtime(provider_instance_id,last_request_at) values($1,$2) on conflict(provider_instance_id) do update set last_request_at=$2`,[exhaustedUnknown,now]);await pool.query(`insert into provider_quota_observations(provider_instance_id,observed_at,window_kind,remaining,reliable) values($1,$2,'month',0,true)`,[exhaustedUnknown,now]);decision=await quota.authorize(exhaustedUnknown,'current');pass(48,!decision.allowed&&decision.next_eligible_at===null&&decision.blocking_reason==='provider_reported_exhausted');
  const reserveObserved=await make('reserve-observed',{month:10000,safety:5,reserve:20});await pool.query(`insert into provider_quota_windows values($1,'month','2026-08-01',7600,now())`,[reserveObserved]);await pool.query(`insert into provider_quota_observations(provider_instance_id,observed_at,window_kind,remaining,resets_at,reliable) values($1,$2,'month',2,'2026-09-01',true)`,[reserveObserved,now]);now=new Date(now.getTime()+1);pass(49,(await quota.authorize(reserveObserved,'current')).allowed);now=new Date(now.getTime()+1);pass(50,(await quota.authorize(reserveObserved,'current')).allowed);now=new Date(now.getTime()+1);pass(51,!(await quota.authorize(reserveObserved,'current')).allowed);
  const observedMulti=await make('observed-multi',{minute:60,hour:500,month:10000});charge=await quota.authorize(observedMulti,'current');await quota.recordOutcome(charge.chargeId,{metadata:{status:200,headers:{}},observation:[{windowKind:'minute',limit:60,remaining:2,resetsAt:new Date(now.getTime()+60000).toISOString(),reliable:true},{windowKind:'hour',limit:500,remaining:100,resetsAt:new Date(now.getTime()+3600000).toISOString(),reliable:true},{windowKind:'month',limit:10000,remaining:7000,resetsAt:'2026-09-01T00:00:00Z',reliable:true}]});const kinds=(await pool.query('select window_kind from provider_quota_observations where provider_instance_id=$1 order by window_kind',[observedMulti])).rows.map(row=>row.window_kind);pass(52,JSON.stringify(kinds)===JSON.stringify(['hour','minute','month']));
  const expiredObservation=await make('expired-observation',{month:10});await pool.query(`insert into provider_quota_observations(provider_instance_id,observed_at,window_kind,remaining,resets_at,reliable) values($1,$2,'month',0,$3,true)`,[expiredObservation,new Date(now.getTime()-3600000),new Date(now.getTime()-1)]);pass(53,(await quota.authorize(expiredObservation,'current')).allowed);
  const discoveryProvider=await make('discovery-deferred',{month:10});await pool.query(`update provider_instances set discovery_enabled=true where id=$1`,[discoveryProvider]);await pool.query(`insert into provider_quota_runtime(provider_instance_id,provider_backoff_until) values($1,$2) on conflict(provider_instance_id) do update set provider_backoff_until=$2`,[discoveryProvider,new Date(now.getTime()+21600000)]);const scheduler=new PersistentSchedulerService({now:()=>new Date(now)});const lease=await scheduler.acquireDueDiscovery('lot55-audit');assert.ok(lease&&lease.id===discoveryProvider);const adapter={discoverChampionships:async context=>{await fetchProviderJson({url:new URL('https://provider.test/discovery'),allowedHosts:['provider.test'],fetchImpl:async()=>{throw new Error('must not emit');},gate:context.requestGate});return {items:[],complete:true,provenance:'provider-discovered'};}};const providerFacade={get:async id=>id===discoveryProvider?{adapter_key:'fixture',config:{}}:null,registry:new Map([['fixture',adapter]]),readSecretForAdapter:async()=>null};const discovery=new ProviderDiscoveryService(providerFacade,quota);const run=await discovery.discover(discoveryProvider,'periodic',{principal:{sub:'lot55-audit',role:'admin',exp:2147483647,auth_method:'technical_hmac'},requestId:'lot55-audit'},()=>scheduler.assertDiscoveryLease(discoveryProvider,'lot55-audit',Number(lease.discovery_lease_generation)));await scheduler.releaseDiscovery(discoveryProvider,'lot55-audit',Number(lease.discovery_lease_generation));pass(54,run.status==='deferred_quota'&&run.request_count===0&&new Date(run.next_eligible_at).getTime()===now.getTime()+21600000&&await scheduler.acquireDueDiscovery('lot55-too-early')===null);now=new Date(now.getTime()+21600001);pass(55,(await scheduler.acquireDueDiscovery('lot55-after-reset'))?.id===discoveryProvider);
  const diagnosticQuota=await make('diagnostic-quota',{minute:1});await quota.authorize(diagnosticQuota,'current');decision=await quota.authorize(diagnosticQuota,'current');let diagnostic=await quota.diagnostics(diagnosticQuota);pass(56,!decision.allowed&&diagnostic.summary.blocking_reason===decision.blocking_reason&&new Date(diagnostic.summary.next_eligible_at).getTime()===new Date(decision.next_eligible_at).getTime());
  const diagnosticInterval=await make('diagnostic-interval',{interval:10});await quota.authorize(diagnosticInterval,'current');decision=await quota.authorize(diagnosticInterval,'current');diagnostic=await quota.diagnostics(diagnosticInterval);pass(57,!decision.allowed&&decision.blocking_reason==='minimum_interval'&&diagnostic.summary.blocking_reason===decision.blocking_reason&&new Date(diagnostic.summary.next_eligible_at).getTime()===new Date(decision.next_eligible_at).getTime());
  await pool.query(`update provider_quota_runtime set next_eligible_at=$2 where provider_instance_id=$1`,[exhaustedUnknown,new Date(now.getTime()+86400000)]);decision=await quota.authorize(exhaustedUnknown,'current');diagnostic=await quota.diagnostics(exhaustedUnknown);pass(58,!decision.allowed&&decision.next_eligible_at===null&&diagnostic.summary.blocking_reason==='provider_reported_exhausted'&&diagnostic.summary.next_eligible_at===null);
  await pool.query(`update provider_quota_runtime set provider_backoff_until=$2 where provider_instance_id=$1`,[back,new Date(now.getTime()+60000)]);decision=await quota.authorize(back,'current');diagnostic=await quota.diagnostics(back);pass(59,!decision.allowed&&decision.blocking_reason==='provider_backoff'&&diagnostic.summary.blocking_reason===decision.blocking_reason&&new Date(diagnostic.summary.next_eligible_at).getTime()===new Date(decision.next_eligible_at).getTime());
  const sameClock=await make('same-clock-observation',{minute:100,hour:100,day:100,month:100});charge=await quota.authorize(sameClock,'current');const sameClockReset=new Date(now.getTime()+60000);await quota.recordOutcome(charge.chargeId,{metadata:{status:200,headers:{}},observation:{windowKind:'minute',limit:100,remaining:2,resetsAt:sameClockReset.toISOString(),reliable:true}});const sameClockFirst=await quota.authorize(sameClock,'current'),sameClockSecond=await quota.authorize(sameClock,'current'),sameClockThird=await quota.authorize(sameClock,'current');pass(60,sameClockFirst.allowed&&sameClockSecond.allowed&&!sameClockThird.allowed&&sameClockThird.blocking_reason==='provider_reported_exhausted');
  now=new Date(sameClockReset.getTime()+1);decision=await quota.authorize(sameClock,'current');diagnostic=await quota.diagnostics(sameClock);pass(61,decision.allowed&&diagnostic.summary.blocking_reason===null&&diagnostic.summary.next_eligible_at===null);
  assert.equal(covered.size,64);console.log('64 cas Lot 5.5 : OK\nREAL PROVIDER REQUESTS = 0\nPROVIDER CREDITS CONSUMED = 0');
}finally{for(const id of providers)await pool.query('delete from provider_instances where id=$1',[id]);for(const id of championships)await pool.query('delete from championships where id=$1',[id]);await pool.end();}
